local addonName, SM = ...

SM.TrollHeritageData = {
    title = "Heritage of the Darkspear",
    description = "Return to the Echo Isles, seek the old loa, and help the Darkspear reclaim a neglected part of their spiritual identity.",
    zone = "Echo Isles / Northern Stranglethorn",
    expansion = "Dragonflight",
    faction = "Horde",
    race = "Troll",
    requiredLevel = 50,
    achievementName = "Heritage of the Darkspear",
    color = { 0.15, 0.55, 0.87 },
    icon = "Interface\\Icons\\inv_misc_tabard_darkspear",
    startQuest = { id = 77869, name = "Return to the Echo Isles", npc = "Zi'guma", location = "Valley of Spirits, Orgrimmar" },
    startMapID = 85,
    startX = 0.3270,
    startY = 0.6470,
    npcDisplayIDs = {
        ["Rokhan"] = 7496,
        ["Master Gadrin"] = 0,
        ["Witch Doctor Tzadah"] = 0,
        ["Kevo ya Siti"] = 0,
        ["Lukou"] = 0,
        ["Jani"] = 0,
    },
    chapters = {
        {
            chapter = "Heritage of the Darkspear",
            summary = "Confront Mueh'zala's influence, recover forgotten loa, and complete a Trial of the Loa worthy of the Darkspear.",
            recap = "The Darkspear were pulled toward old fears and dark power, but chose another path. By restoring their ties to Kevo ya Siti, Lukou, and Jani, you helped your people remember who they are and what they stand for.",
            quests = {
                { id = 77869, name = "Return to the Echo Isles", npc = "Zi'guma" },
                { id = 77871, name = "De Old Loa", npc = "Master Gadrin" },
                { id = 77874, name = "De Loa of de Past", npc = "Rokhan" },
                { id = 77879, name = "Stalking the Stalker", npc = "Rokhan" },
                { id = 77881, name = "There is Another", npc = "Kevo ya Siti" },
                { id = 77880, name = "Looking for Lukou", npc = "Rokhan" },
                { id = 77877, name = "One with the Loa", npc = "Kevo ya Siti" },
                { id = 78875, name = "The Unkillable", npc = "Rokhan" },
                { id = 77882, name = "Stolen but Not Forgotten", npc = "Rokhan" },
                { id = 77894, name = "Heart of Lukou", npc = "Rokhan" },
                { id = 77898, name = "Honor and Tribute", npc = "Rokhan" },
                { id = 77899, name = "The Rush'kah", npc = "Witch Doctor Tzadah" },
                { id = 77900, name = "The Loa Trials", npc = "Rokhan" },
                { id = 77903, name = "De Power of Death", npc = "Rokhan" },
                { id = 77902, name = "Ritual Recovery", npc = "Lukou" },
                { id = 77901, name = "Retraining the Trainees", npc = "Kevo ya Siti" },
                { id = 77905, name = "Avatar of Mueh'zala", npc = "Rokhan" },
                { id = 77906, name = "De Darkspear Loa", npc = "Rokhan" },
            },
        },
    },
}

return SM
