local addonName, SM = ...

local ICECROWN_QUEST_NAMES = {
    [12806] = "To the Rise with all Due Haste!",
    [12807] = "The Story Thus Far...",
    [12810] = "Blood in the Water",
    [12813] = "From Their Corpses, Rise!",
    [12814] = "You'll Need a Gryphon",
    [12815] = "No Fly Zone",
    [12838] = "Intelligence Gathering",
    [12839] = "The Grand (Admiral's) Plan",
    [12840] = "In Strict Confidence",
    [12847] = "Second Chances",
    [12852] = "The Admiral Revealed",
    [12887] = "It's All Fun and Games",
    [12891] = "I Have an Idea, But First...",
    [12892] = "It's All Fun and Games",
    [12893] = "Free Your Mind",
    [12896] = "If He Cannot Be Turned",
    [12897] = "If He Cannot Be Turned",
    [12898] = "The Shadow Vault",
    [12899] = "The Shadow Vault",
    [12938] = "The Duke",
    [12939] = "Honor Challenge",
    [12943] = "Shadow Vault Decree",
    [12949] = "Get the Key",
    [12951] = "Let the Baron Know",
    [12955] = "Eliminate the Competition",
    [12982] = "Ebon Blade Prisoners",
    [12992] = "Crush Dem Vrykuls!",
    [12995] = "Leave Our Mark",
    [12999] = "The Bone Witch",
    [13008] = "Scourge Tactics",
    [13036] = "Honor Above All Else",
    [13039] = "Defending The Vanguard",
    [13040] = "Curing The Incurable",
    [13042] = "Deep in the Bowels of The Underhalls",
    [13043] = "The Sum is Greater than the Parts",
    [13044] = "If There Are Survivors...",
    [13045] = "Into The Wild Green Yonder",
    [13059] = "Revenge for the Vargul",
    [13068] = "A Tale of Valor",
    [13069] = "Shoot 'Em Up",
    [13070] = "A Cold Front Approaches",
    [13071] = "Vile Like Fire!",
    [13072] = "A Hero Remains",
    [13073] = "The Keeper's Favor",
    [13074] = "Hope Within the Emerald Nightmare",
    [13075] = "The Boon of Remulos",
    [13076] = "Time Yet Remains",
    [13077] = "The Touch of an Aspect",
    [13078] = "Dahlia's Tear",
    [13079] = "The Boon of Alexstrasza",
    [13080] = "Hope Yet Remains",
    [13081] = "The Will of the Naaru",
    [13082] = "The Boon of A'dal",
    [13083] = "Light Within the Darkness",
    [13084] = "Vandalizing Jotunheim",
    [13085] = "Vaelen Has Returned",
    [13086] = "The Last Line Of Defense",
    [13091] = "The Art of Being a Water Terror",
    [13092] = "Reading the Bones",
    [13093] = "Reading the Bones",
    [13104] = "Once More Unto The Breach, Hero",
    [13105] = "Once More Unto The Breach, Hero",
    [13106] = "Blackwatch",
    [13110] = "The Restless Dead",
    [13117] = "Where Are They Coming From?",
    [13118] = "The Purging Of Scourgeholme",
    [13119] = "Destroying the Altars",
    [13120] = "Death's Gaze",
    [13121] = "Through the Eye",
    [13122] = "The Scourgestone",
    [13125] = "The Air Stands Still",
    [13130] = "The Stone That Started A Revolution",
    [13133] = "Find the Ancient Hero",
    [13134] = "Spill Their Blood",
    [13135] = "It Could Kill Us All",
    [13136] = "Jagged Shards",
    [13137] = "Not-So-Honorable Combat",
    [13138] = "I'm Smelting... Smelting!",
    [13139] = "Into The Frozen Heart Of Northrend",
    [13140] = "The Runesmiths of Malykriss",
    [13141] = "The Battle For Crusaders' Pinnacle",
    [13142] = "Banshee's Revenge",
    [13143] = "New Recruit",
    [13144] = "Killing Two Scourge With One Skeleton",
    [13145] = "The Vile Hold",
    [13146] = "Generosity Abounds",
    [13147] = "Matchmaker",
    [13152] = "A Visit to the Doctor",
    [13155] = "Vereth the Cunning",
    [13157] = "The Crusaders' Pinnacle",
    [13160] = "Stunning View",
    [13161] = "The Rider of the Unholy",
    [13162] = "The Rider of Frost",
    [13163] = "The Rider of Blood",
    [13164] = "The Fate of Bloodbane",
    [13168] = "Parting Gifts",
    [13169] = "An Undead's Best Friend",
    [13170] = "Honor is for the Weak",
    [13171] = "From Whence They Came",
    [13172] = "Seeds of Chaos",
    [13174] = "Amidst the Confusion",
    [13279] = "Basic Chemistry",
    [13295] = "Basic Chemistry",
    [13211] = "By Fire Be Purged",
    [13212] = "He's Gone to Pieces",
    [13213] = "Battle at Valhalas",
    [13214] = "Battle at Valhalas: Fallen Heroes",
    [13215] = "Battle at Valhalas: Khit'rix the Dark Master",
    [13216] = "Battle at Valhalas: The Return of Sigrid Iceborn",
    [13217] = "Battle at Valhalas: Carnage!",
    [13218] = "Battle at Valhalas: Thane Deathblow",
    [13219] = "Battle at Valhalas: Final Challenge",
    [13220] = "Putting Olakin Back Together Again",
    [13221] = "I'm Not Dead Yet!",
    [13224] = "Orgrim's Hammer",
    [13225] = "The Skybreaker",
    [13226] = "Judgment Day Comes!",
    [13227] = "Judgment Day Comes!",
    [13228] = "The Broken Front",
    [13229] = "I'm Not Dead Yet!",
    [13230] = "Avenge Me!",
    [13231] = "The Broken Front",
    [13232] = "Finish Me!",
    [13233] = "No Mercy!",
    [13234] = "Make Them Pay!",
    [13235] = "The Flesh Giant Champion",
    [13236] = "Army of the Damned",
    [13237] = "Poke and Prod",
    [13238] = "Good For Something?",
    [13260] = "Takes One to Know One",
    [13261] = "Volatility",
    [13264] = "That's Abominable!",
    [13277] = "Against the Giants",
    [13278] = "Coprous the Defiled",
    [13287] = "Poke and Prod",
    [13288] = "That's Abominable!",
    [13289] = "That's Abominable!",
    [13290] = "Your Attention, Please",
    [13291] = "Borrowed Technology",
    [13292] = "The Solution Solution",
    [13294] = "Against the Giants",
    [13297] = "Putting the Hertz: The Valley of Lost Hope",
    [13298] = "Coprous the Defiled",
    [13300] = "Slaves to Saronite",
    [13302] = "Slaves to Saronite",
    [13318] = "Drag and Drop",
    [13319] = "Drag and Drop",
    [13330] = "Blood of the Chosen",
    [13336] = "Blood of the Chosen",
    [13346] = "No Rest For The Wicked",
    [13351] = "Sneak Preview",
    [13352] = "Drag and Drop",
    [13353] = "Drag and Drop",
    [13354] = "Chain of Command",
    [13355] = "Cannot Reproduce",
    [13356] = "Retest Now",
    [13357] = "Retest Now",
    [13358] = "Not a Bug",
    [13365] = "Not a Bug",
    [13366] = "Need More Info",
    [13367] = "No Rest For The Wicked",
    [13368] = "No Rest For The Wicked",
    [13258] = "Opportunity",
    [13259] = "Establishing Superiority",
    [13262] = "Blow it Up!",
    [13263] = "A Short Fuse",
    [13271] = "A Voice in the Dark",
    [13275] = "Time to Hide",
    [13280] = "King of the Mountain",
    [13282] = "Return to the Surface",
    [13283] = "King of the Mountain",
    [13284] = "Assault by Ground",
    [13293] = "Get to Ymirheim!",
    [13296] = "Get to Ymirheim!",
    [13301] = "Assault by Ground",
    [13304] = "Field Repairs",
    [13305] = "Do Your Worst",
    [13308] = "Mind Tricks",
    [13309] = "Assault by Air",
    [13310] = "Assault by Air",
    [13316] = "The Guardians of Corp'rethar",
    [13338] = "The Guardians of Corp'rethar",
    [13340] = "Joining the Assault",
    [13341] = "Joining the Assault",
    [13348] = "Futility",
    [13349] = "Cradle of the Frostbrood",
    [13359] = "Where Dragons Fell",
    [13360] = "Time for Answers",
    [13361] = "The Hunter and the Prince",
    [13362] = "Knowledge is a Terrible Burden",
    [13363] = "Argent Aid",
    [13364] = "Tirion's Gambit",
    [13373] = "Fringe Science Benefits",
    [13374] = "Amped for Revolt!",
    [13376] = "Total Ohmage: The Valley of Lost Hope!",
    [13379] = "Green Technology",
    [13380] = "Leading the Charge",
    [13381] = "Watts My Target",
    [13382] = "Putting the Hertz: The Valley of Lost Hope",
    [13383] = "Killohertz",
    [13386] = "Exploiting an Opening",
    [13387] = "Securing the Perimeter",
    [13388] = "Set it Off!",
    [13389] = "A Short Fuse",
    [13390] = "A Voice in the Dark",
    [13391] = "Time to Hide",
    [13392] = "Return to the Surface",
    [13393] = "Field Repairs",
    [13394] = "Do Your Worst",
    [13395] = "Army of the Damned",
    [13396] = "Futility",
    [13397] = "Sindragosa's Fall",
    [13398] = "Where Dragons Fell",
    [13399] = "Time for Answers",
    [13400] = "The Hunter and the Prince",
    [13401] = "Knowledge is a Terrible Burden",
    [13402] = "Tirion's Help",
    [13403] = "Tirion's Gambit",
    [13404] = "Static Shock Troops: the Bombardment",
    [13406] = "Riding the Wavelength: The Bombardment",
    [13418] = "Preparations for War",
    [13419] = "Preparations for War",
    [13481] = "Let's Get Out of Here!",
    [13482] = "Let's Get Out of Here",
    [13592] = "A Valiant's Field Training",
    [13593] = "Valiant Of Stormwind",
    [13600] = "A Worthy Weapon",
    [13603] = "A Blade Fit For A Champion",
    [13616] = "The Edge Of Winter",
    [13625] = "Learning The Reins",
    [13633] = "The Black Knight of Westfall?",
    [13634] = "The Black Knight of Silverpine?",
    [13641] = "The Seer's Crystal",
    [13643] = "The Stories Dead Men Tell",
    [13654] = "There's Something About the Squire",
    [13663] = "The Black Knight's Orders",
    [13664] = "The Black Knight's Fall",
    [13665] = "The Grand Melee",
    [13666] = "A Blade Fit For A Champion",
    [13667] = "The Argent Tournament",
    [13668] = "The Argent Tournament",
    [13669] = "A Worthy Weapon",
    [13670] = "The Edge Of Winter",
    [13671] = "Training In The Field",
    [13672] = "Up To The Challenge",
    [13673] = "A Blade Fit For A Champion",
    [13674] = "A Worthy Weapon",
    [13675] = "The Edge Of Winter",
    [13676] = "Training In The Field",
    [13677] = "Learning The Reins",
    [13678] = "Up To The Challenge",
    [13679] = "The Aspirant's Challenge",
    [13680] = "The Aspirant's Challenge",
    [13682] = "Threat From Above",
    [13684] = "A Valiant Of Stormwind",
    [13685] = "A Valiant Of Ironforge",
    [13688] = "A Valiant Of Gnomeregan",
    [13689] = "A Valiant Of Darnassus",
    [13690] = "A Valiant Of The Exodar",
    [13691] = "A Valiant Of Orgrimmar",
    [13693] = "A Valiant Of Sen'jin",
    [13694] = "A Valiant Of Thunder Bluff",
    [13695] = "A Valiant Of Undercity",
    [13696] = "A Valiant Of Silvermoon",
    [13697] = "The Valiant's Charge",
    [13699] = "The Valiant's Challenge",
    [13702] = "A Champion Rises",
    [13703] = "Valiant Of Ironforge",
    [13704] = "Valiant Of Gnomeregan",
    [13705] = "Valiant Of The Exodar",
    [13706] = "Valiant Of Darnassus",
    [13707] = "Valiant Of Orgrimmar",
    [13708] = "Valiant Of Sen'jin",
    [13709] = "Valiant Of Thunder Bluff",
    [13710] = "Valiant Of Undercity",
    [13711] = "Valiant Of Silvermoon",
    [13713] = "The Valiant's Challenge",
    [13714] = "The Valiant's Charge",
    [13715] = "The Valiant's Charge",
    [13716] = "The Valiant's Charge",
    [13717] = "The Valiant's Charge",
    [13718] = "The Valiant's Charge",
    [13719] = "The Valiant's Charge",
    [13720] = "The Valiant's Charge",
    [13721] = "The Valiant's Charge",
    [13722] = "The Valiant's Charge",
    [13723] = "The Valiant's Challenge",
    [13724] = "The Valiant's Challenge",
    [13725] = "The Valiant's Challenge",
    [13726] = "The Valiant's Challenge",
    [13727] = "The Valiant's Challenge",
    [13728] = "The Valiant's Challenge",
    [13729] = "The Valiant's Challenge",
    [13731] = "The Valiant's Challenge",
    [13732] = "A Champion Rises",
    [13733] = "A Champion Rises",
    [13734] = "A Champion Rises",
    [13735] = "A Champion Rises",
    [13736] = "A Champion Rises",
    [13737] = "A Champion Rises",
    [13738] = "A Champion Rises",
    [13739] = "A Champion Rises",
    [13740] = "A Champion Rises",
    [13741] = "A Blade Fit For A Champion",
    [13742] = "A Worthy Weapon",
    [13743] = "The Edge Of Winter",
    [13744] = "A Valiant's Field Training",
    [13745] = "The Grand Melee",
    [13746] = "A Blade Fit For A Champion",
    [13747] = "A Worthy Weapon",
    [13748] = "The Edge Of Winter",
    [13749] = "A Valiant's Field Training",
    [13750] = "The Grand Melee",
    [13752] = "A Blade Fit For A Champion",
    [13753] = "A Worthy Weapon",
    [13754] = "The Edge Of Winter",
    [13755] = "A Valiant's Field Training",
    [13756] = "The Grand Melee",
    [13757] = "A Blade Fit For A Champion",
    [13758] = "A Worthy Weapon",
    [13759] = "The Edge Of Winter",
    [13760] = "A Valiant's Field Training",
    [13761] = "The Grand Melee",
    [13762] = "A Blade Fit For A Champion",
    [13763] = "A Worthy Weapon",
    [13764] = "The Edge Of Winter",
    [13765] = "A Valiant's Field Training",
    [13767] = "The Grand Melee",
    [13768] = "A Blade Fit For A Champion",
    [13769] = "A Worthy Weapon",
    [13770] = "The Edge Of Winter",
    [13771] = "A Valiant's Field Training",
    [13772] = "The Grand Melee",
    [13773] = "A Blade Fit For A Champion",
    [13774] = "A Worthy Weapon",
    [13775] = "The Edge Of Winter",
    [13776] = "A Valiant's Field Training",
    [13777] = "The Grand Melee",
    [13778] = "A Blade Fit For A Champion",
    [13779] = "A Worthy Weapon",
    [13780] = "The Edge Of Winter",
    [13781] = "A Valiant's Field Training",
    [13782] = "The Grand Melee",
    [13783] = "A Blade Fit For A Champion",
    [13784] = "A Worthy Weapon",
    [13785] = "The Edge Of Winter",
    [13786] = "A Valiant's Field Training",
    [13787] = "The Grand Melee",
    [13788] = "Threat From Above",
    [13789] = "Taking Battle To The Enemy",
    [13790] = "Among the Champions",
    [13791] = "Taking Battle To The Enemy",
    [13793] = "Among the Champions",
    [13794] = "Eadric the Pure",
    [13795] = "The Scourgebane",
    [13809] = "Threat From Above",
    [13810] = "Taking Battle To The Enemy",
    [13811] = "Among the Champions",
    [13812] = "Threat From Above",
    [13813] = "Taking Battle To The Enemy",
    [13814] = "Among the Champions",
    [13828] = "Mastery Of Melee",
    [13829] = "Mastery Of Melee",
    [13835] = "Mastery Of The Shield-Breaker",
    [13837] = "Mastery Of The Charge",
    [13838] = "Mastery Of The Shield-Breaker",
    [13839] = "Mastery Of The Charge",
    [13846] = "Contributin' To The Cause",
    [13847] = "At The Enemy's Gates",
    [13851] = "At The Enemy's Gates",
    [13852] = "At The Enemy's Gates",
    [13854] = "At The Enemy's Gates",
    [13855] = "At The Enemy's Gates",
    [13856] = "At The Enemy's Gates",
    [13857] = "At The Enemy's Gates",
    [13858] = "At The Enemy's Gates",
    [13859] = "At The Enemy's Gates",
    [13860] = "At The Enemy's Gates",
    [13861] = "Battle Before The Citadel",
    [13862] = "Battle Before The Citadel",
    [13863] = "Battle Before The Citadel",
    [13864] = "Battle Before The Citadel",
    [14016] = "The Black Knight's Curse",
    [14017] = "The Black Knight's Fate",
    [14074] = "A Leg Up",
    [14076] = "Breakfast Of Champions",
    [14077] = "The Light's Mercy",
    [14080] = "Stop The Aggressors",
    [14090] = "Gormok Wants His Snobolds",
    [14092] = "Breakfast Of Champions",
    [14095] = "Identifying the Remains",
    [14096] = "You've Really Done It This Time, Kul",
    [14101] = "Drottinn Hrothgar",
    [14102] = "Mistcaller Yngvar",
    [14104] = "Ornolf The Scarred",
    [14105] = "Deathspeaker Kharos",
    [14107] = "The Fate Of The Fallen",
    [14108] = "Get Kraken!",
    [14112] = "What Do You Feed a Yeti, Anyway?",
    [14136] = "Rescue at Sea",
    [14140] = "Stop The Aggressors",
    [14141] = "Gormok Wants His Snobolds",
    [14142] = "You've Really Done It This Time, Kul",
    [14143] = "A Leg Up",
    [14144] = "The Light's Mercy",
    [14145] = "What Do You Feed a Yeti, Anyway?",
    [14152] = "Rescue at Sea",
    [14441] = "Garrosh's Autograph",
    [14443] = "The Battered Hilt",
    [14444] = "What The Dragons Know",
    [24442] = "Battle Plans Of The Kvaldir",
    [24454] = "Return To Caladis Brightspear",
    [24461] = "Reforging The Sword",
    [24476] = "Tempering The Blade",
    [24480] = "The Halls Of Reflection",
    [24522] = "Journey To The Sunwell",
    [24553] = "The Purification of Quel'Delar",
    [24554] = "The Battered Hilt",
    [24555] = "What The Dragons Know",
    [24558] = "Return To Myralion Sunblaze",
    [24559] = "Reforging The Sword",
    [24560] = "Tempering The Blade",
    [24561] = "The Halls Of Reflection",
    [24562] = "Journey To The Sunwell",
    [24564] = "The Purification of Quel'Delar",
    [24594] = "The Purification of Quel'Delar",
    [24595] = "The Purification of Quel'Delar",
    [24596] = "The Purification of Quel'Delar",
    [24598] = "The Purification of Quel'Delar",
    [24795] = "A Victory For The Silver Covenant",
    [24796] = "A Victory For The Silver Covenant",
    [24798] = "A Victory For The Sunreavers",
    [24799] = "A Victory For The Sunreavers",
    [24800] = "A Victory For The Sunreavers",
    [24801] = "A Victory For The Sunreavers",
}

local function BuildQuestEntries(ids, npcLabel)
    local quests = {}
    for i = 1, #ids do
        local id = ids[i]
        local name = ICECROWN_QUEST_NAMES[id] or ("Icecrown Quest " .. id)
        quests[#quests + 1] = { id = id, name = name, npc = npcLabel or "Icecrown Campaign" }
    end
    return quests
end

-- =============================================================================
-- Wrath of the Lich King: The Frozen Throne (Arthas Menethil)
-- A curated campaign of quests and dungeons centered on Arthas' fall.
-- =============================================================================

SM.FrozenThroneData = {
    title = "The Frozen Throne",
    achievementName = "Arthas Menethil",
    achievements = {
        -- Dragonblight / Wrathgate
        35,     -- Might of Dragonblight (full Dragonblight zone story)
        547,    -- Veteran of the Wrathgate (the Wrathgate chain specifically)
        -- Icecrown questing
        40,     -- Icecrown: The Final Goal (full Icecrown zone story)
        -- Northrend-wide
        41,     -- Loremaster of Northrend
        -- The Frozen Halls
        4516,   -- The Forge of Souls (Normal)
        4517,   -- The Pit of Saron (Normal)
        4518,   -- The Halls of Reflection (Normal)
        -- Icecrown Citadel
        4532,   -- Fall of the Lich King (10 player)
        4530,   -- The Frozen Throne (10 player) — grants Kingslayer title
    },
    description = "Walk the long road that turned Prince Arthas Menethil into the Lich King — and the longer road to unmake him. It begins in Stratholme, where a prince purged his own people to save them, and ends in Icecrown, where a king sits frozen on a throne of his own making. Between are the dragon-haunted plains of Dragonblight, the howling reach of Northrend, and a campaign waged in the long shadow of Frostmourne. By the time you reach the spire, the question is no longer whether Arthas can be killed — but who will pay the price to do it.",
    zone = "Dragonblight / Icecrown",
    expansion = "Wrath of the Lich King",
    color = { 0.45, 0.72, 0.95 },  -- Icy blue
    icon = 341221,
    adventureGuideInstanceName = "Icecrown Citadel",

    startQuest = { id = 12495, name = "Audience With The Dragon Queen", npc = "Alexstrasza the Life-Binder", location = "Wyrmrest Temple, Dragonblight" },
    startMapID = 115, -- Dragonblight
    startX = 0.5900,
    startY = 0.5400,

    npcLocations = {
        -- Key figures
        ["Alexstrasza the Life-Binder"] = { mapID = 115, x = 0.5900, y = 0.5400 },
        ["Highlord Bolvar Fordragon"]  = { mapID = 115, x = 0.7610, y = 0.6310 },
        ["Saurfang the Younger"]       = { mapID = 115, x = 0.3780, y = 0.2300 },
        ["Highlord Tirion Fordring"]   = { mapID = 118, x = 0.7600, y = 0.2000 },
        ["Thassarian"]                 = { mapID = 118, x = 0.7900, y = 0.7200 },
        ["Koltira Deathweaver"]        = { mapID = 118, x = 0.4300, y = 0.1900 },
        ["Lady Jaina Proudmoore"]      = { mapID = 125, x = 0.5500, y = 0.8600 },
        ["Lady Sylvanas Windrunner"]   = { mapID = 125, x = 0.5500, y = 0.8600 },
        ["Martin Victus"]              = { mapID = 125, x = 0.5600, y = 0.5700 },
        ["Darkspeaker R'khem"]          = { mapID = 118, x = 0.5500, y = 0.5600 },
        ["Aurochs Grimbane"]         = { mapID = 118, x = 0.2000, y = 0.4800 },
    },

    npcDisplayIDs = {
        ["Alexstrasza the Life-Binder"] = 24560,
        ["Highlord Bolvar Fordragon"]  = 5566,
        ["Saurfang the Younger"]       = 31785,
        ["Highlord Tirion Fordring"]   = 31011,
        ["Thassarian"]                 = 26608,
        ["Koltira Deathweaver"]        = 25048,
        ["Lady Jaina Proudmoore"]      = 2970,
        ["Lady Sylvanas Windrunner"]   = 28213,
        ["Martin Victus"]              = 30696,
        ["Emissary Brighthoof"]        = 23805,
        ["High Commander Halford Wyrmbane"] = 24348,
        ["Chief Plaguebringer Middleton"] = 30007,
        ["Chromie"]                   = 24877,
        ["Baron Sliver"]              = 28407,
        ["Vereth the Cunning"]        = 29145,
        ["Matthias Lehner"]           = 27522,
        ["Gorkun Ironskull"]          = 27937,
        ["Dark Ranger Vorel"]         = 30686,
        ["High Captain Justin Bartlett"] = 26982,
        ["Sky-Reaver Korm Blackscar"] = 27336,
        ["Warbringer Davos Rioht"]    = 27900,
        ["Darkspeaker R'khem"]       = 28164,
    },

    chapterDisplayIDs = {
        -- Dragonblight
        ["The Dragonblight Campaign"]             = 24351,  -- Duke August Foehammer (Alliance)
        ["Into the Dragonblight"]                 = 23805,  -- Emissary Brighthoof (Horde)
        ["The Nerubian Menace"]                   = 23806,  -- Overlord Agmar (Horde)
        ["Blood of the Taunka"]                   = 23976,  -- Icemist (Horde)
        ["The Forsaken Plague"]                   = 23875,  -- Chief Plaguebringer Middleton (Horde)
        -- Wyrmrest Temple
        ["Wings of the Red Flight"]               = 24879,  -- Highlord Bolvar Fordragon (Alliance)
        ["The Kor'kron at Wyrmrest"]              = 23034,  -- Saurfang the Younger (Horde)
        -- The Wrathgate
        ["The Wrathgate"]                         = 24879,  -- Highlord Bolvar Fordragon (Alliance)
        ["The Warsong at the Wrathgate"]          = 23034,  -- Saurfang the Younger (Horde)
        -- Flashback
        ["The Culling of Stratholme"]             = 24877,  -- Chromie
        -- Icecrown — hub-to-hub journey from the Argent Vanguard to the citadel.
        ["Argent Vanguard"]                       = 31011,  -- Highlord Tirion Fordring
        ["Valley of Echoes"]                      = 31011,  -- Father Gustav / Ebon Watcher
        ["Crusader's Pinnacle"]                   = 31011,  -- Highlord Tirion Fordring
        ["The Skybreaker"]                        = 26982,  -- High Captain Justin Bartlett
        ["Orgrim's Hammer"]                       = 27336,  -- Sky-Reaver Korm Blackscar
        ["Saronite Mines"]                        = 28164,  -- Darkspeaker R'khem
        ["The Shadow Vault"]                      = 28407,  -- Baron Sliver
        ["Blackwatch"]                            = 26608,  -- Grimly / Olakin Sainrith
        ["Jotunheim"]                             = 26608,  -- Uzo Deathcaller / Bragi
        ["Death's Rise"]                          = 28407,  -- Orbaz Bloodbane
        ["Icecrown Citadel"]                      = 30686,  -- Sergeant Stackhammer / Kregga
        ["First Legion Forward Camp"]             = 27522,  -- Matthias Lehner
        ["Sindragosa's Fall"]                     = 27522,  -- Matthias Lehner
        -- Endgame
        ["The Frozen Halls"]                      = 30696,  -- Martin Victus
        ["Fall of the Lich King"]                 = 31011,  -- Highlord Tirion Fordring
    },

    chapters = {
        -- ----------------------------------------------------------------
        -- Dragonblight (Alliance) — the 7th Legion's road to the Wrathgate.
        -- ----------------------------------------------------------------
        {
            chapter = "The Dragonblight Campaign",
            summary = "Hold Wintergarde Keep against the tide rolling down from Naxxramas.",
            recap = "Wintergarde Keep clings to the broken edge of the Dragonblight, pinned between Naxxramas overhead and the plaguebearers boiling up from the Carrion Fields. Duke August Foehammer holds what he can. The 7th Legion bleeds for every mile of frozen ground. High Commander Wyrmbane has orders from Highlord Bolvar Fordragon — push east, past the dragonshrines, toward a black gate in a black mountain.",
            portraitDisplayID = 24351,
            faction = "Alliance",
            quests = {
                { id = 12325, name = "Into Hostile Territory", npc = "Duke August Foehammer", faction = "Alliance" },
                { id = 12326, name = "Steamtank Surprise", npc = "Duke August Foehammer", faction = "Alliance" },
                { id = 12455, name = "Scattered To The Wind", npc = "Ambo Cash", faction = "Alliance" },
                { id = 12457, name = "The Chain Gun And You", npc = "Ambo Cash", faction = "Alliance" },
                { id = 12463, name = "Plunderbeard Must Be Found!", npc = "Ambo Cash", faction = "Alliance" },
                { id = 12465, name = "Plunderbeard's Journal", npc = "Ambo Cash", faction = "Alliance" },
                { id = 12466, name = "Chasing Icestorm: The 7th Legion Front", npc = "Ambo Cash", faction = "Alliance" },
                { id = 12467, name = "Chasing Icestorm: Thel'zan's Phylactery", npc = "Legion Commander Tyralion", faction = "Alliance" },
                { id = 12472, name = "Finality", npc = "Legion Commander Yorik", faction = "Alliance" },
                { id = 12473, name = "An End And A Beginning", npc = "Legion Commander Yorik", faction = "Alliance" },
                { id = 12474, name = "To Fordragon Hold!", npc = "High Commander Halford Wyrmbane", faction = "Alliance" },
            },
        },

        -- ----------------------------------------------------------------
        -- Dragonblight (Horde) — Agmar's Hammer and the side chains that
        -- feed into it.
        -- ----------------------------------------------------------------
        {
            chapter = "Into the Dragonblight",
            summary = "Swear the blood oath at Agmar's Hammer and dig the Horde's claws into the frozen plain.",
            recap = "The Horde's banner flies over Agmar's Hammer, driven into the permafrost like a spear into a cold chest. Emissary Brighthoof calls for warriors willing to bind themselves to the Warchief's campaign. Overlord Agmar tolerates no softness — the Scourge presses on every side, and a red-eyed gate on the horizon waits to be broken.",
            portraitDisplayID = 23805,
            faction = "Horde",
            quests = {
                { id = 11978, name = "Into the Fold", npc = "Emissary Brighthoof", faction = "Horde" },
                { id = 11983, name = "Blood Oath of the Horde", npc = "Emissary Brighthoof", faction = "Horde" },
                { id = 12008, name = "Agmar's Hammer", npc = "Overlord Agmar", faction = "Horde" },
            },
        },
        {
            chapter = "The Nerubian Menace",
            summary = "Crush the Anub'ar climbing up from the ruins of a dead empire.",
            recap = "The Anub'ar Nerubians boil up from the Pit of Narjun — spider-warriors of a civilization that should have stayed dead. They strike the Horde's supply lines by night and drag the wounded into the dark by morning. Senior Sergeant Juktok wants them ended at the source. Valnok Windrager is already saddling the wyverns. Agmar will not leave this flank open.",
            portraitDisplayID = 23806,
            faction = "Horde",
            quests = {
                { id = 12034, name = "Victory Nears...", npc = "Overlord Agmar", faction = "Horde" },
                { id = 12036, name = "From the Depths of Azjol-Nerub", npc = "Senior Sergeant Juktok", faction = "Horde" },
                { id = 12053, name = "The Might of the Horde", npc = "Senior Sergeant Juktok", faction = "Horde" },
                { id = 12071, name = "Attack by Air!", npc = "Valnok Windrager", faction = "Horde" },
                { id = 12072, name = "Blightbeasts be Damned", npc = "Valnok Windrager", faction = "Horde" },
            },
        },
        {
            chapter = "Blood of the Taunka",
            summary = "Rescue a captive High Chief and bring a new people into the Horde.",
            recap = "Greatmother Icemist weeps over a quiet fire. Her son is chained somewhere beneath this frozen plain, and her daughter Banthok is ready to cut every Anub'ar web in the world to bring him home. The Taunka are a proud and wounded people, shaggy cousins to the Tauren whose strength the Scourge has long bled for sport. If they rise again, they rise with the Horde.",
            portraitDisplayID = 23976,
            faction = "Horde",
            quests = {
                { id = 12063, name = "Strength of Icemist", npc = "Greatmother Icemist", faction = "Horde" },
                { id = 12064, name = "Chains of the Anub'ar", npc = "Banthok Icemist", faction = "Horde" },
                { id = 12069, name = "Return of the High Chief", npc = "Banthok Icemist", faction = "Horde" },
                { id = 12140, name = "All Hail Roanauk!", npc = "Roanauk Icemist", faction = "Horde" },
            },
        },
        {
            chapter = "The Forsaken Plague",
            summary = "Put the Royal Apothecary Society's new weapon through its paces.",
            recap = "Chief Plaguebringer Middleton has been busy in the Carrion Fields. He has something new to test — a blight meant to undo the Scourge where steel cannot reach. The formula wants a subject. Middleton smiles through gritted teeth and swears the first dose is always the worst. Whatever the Apothecaries are cooking under the Horde's banner, it may reshape this war.",
            portraitDisplayID = 23875,
            faction = "Horde",
            quests = {
                { id = 12189, name = "Imbeciles Abound!", npc = "Chief Plaguebringer Middleton", faction = "Horde" },
                { id = 12188, name = "The Forsaken Blight and You: How Not to Die", npc = "Chief Plaguebringer Middleton", faction = "Horde" },
                { id = 12200, name = "Emerald Dragon Tears", npc = "Chief Plaguebringer Middleton", faction = "Horde" },
                { id = 12218, name = "Spread the Good Word", npc = "Chief Plaguebringer Middleton", faction = "Horde" },
                { id = 12221, name = "The Forsaken Blight", npc = "Doctor Sintar Malefious", faction = "Horde" },
            },
        },

        -- ----------------------------------------------------------------
        -- Wyrmrest Temple — both factions petition the Life-Binder.
        -- ----------------------------------------------------------------
        {
            chapter = "Wings of the Red Flight",
            summary = "Ride to Wyrmrest Temple and kneel before Alexstrasza, the Life-Binder.",
            recap = "Highlord Bolvar Fordragon leads you up the spiral of Wyrmrest Temple. Alexstrasza the Life-Binder has watched the war in Dragonblight with ancient, weary eyes. She owes the Alliance nothing. She owes the living everything. If she can be moved, her fire will answer for Azeroth's dead — and a ruby wing will carry you over ground no army could cross.",
            portraitDisplayID = 24879,
            faction = "Alliance",
            quests = {
                { id = 12495, name = "Audience With The Dragon Queen", npc = "Highlord Bolvar Fordragon", faction = "Alliance" },
                { id = 12497, name = "Galakrond and the Scourge", npc = "Alexstrasza the Life-Binder" },
                { id = 12498, name = "On Ruby Wings", npc = "Torastrasza" },
            },
        },
        {
            chapter = "The Kor'kron at Wyrmrest",
            summary = "Saurfang leads the Horde up the spiral of Wyrmrest to bargain with the Dragon Queen.",
            recap = "Saurfang the Younger calls you to the Kor'kron Vanguard. The Taunka are blood-sworn, the Nerubians silenced, and the Forsaken have their weapons. The old Orc himself takes you to Wyrmrest Temple — to kneel, or rather to bargain, before Alexstrasza the Life-Binder. The dragons remember every Horde blade that ever flashed in anger at the Second War. Whether they answer the Warchief's call is another matter.",
            portraitDisplayID = 23034,
            faction = "Horde",
            quests = {
                { id = 12224, name = "The Kor'kron Vanguard!", npc = "Saurfang the Younger", faction = "Horde" },
                { id = 12496, name = "Audience With The Dragon Queen", npc = "Saurfang the Younger", faction = "Horde" },
                { id = 12497, name = "Galakrond and the Scourge", npc = "Alexstrasza the Life-Binder" },
                { id = 12498, name = "On Ruby Wings", npc = "Torastrasza" },
            },
        },

        -- ----------------------------------------------------------------
        -- The Wrathgate — the march that ends the Dragonblight arc.
        -- Culminates in the iconic cinematic at Angrathar.
        -- ----------------------------------------------------------------
        {
            chapter = "The Wrathgate",
            summary = "March with Bolvar Fordragon to the black gate at the edge of Icecrown.",
            recap = "Angrathar. The black gate beyond which the Lich King's frozen fortress waits. Bolvar Fordragon has gathered every shield the Alliance can spare. Dragons circle above. Somewhere to the east, the Horde marches its own road to the same gate. Ahead, the Scourge stands in ranks that do not end. This is the road to the Lich King's door.",
            portraitDisplayID = 24879,
            faction = "Alliance",
            quests = {
                { id = 12499, name = "Return To Angrathar", npc = "Highlord Bolvar Fordragon", faction = "Alliance" },
            },
        },
        {
            chapter = "The Warsong at the Wrathgate",
            summary = "Saurfang leads the charge on the gate to the Lich King's domain.",
            recap = "Angrathar. The Wrathgate. The final road to the Lich King's own door. Saurfang the Younger takes point, every Orc behind him blood-mad and ready for the reckoning. Somewhere to the west, the Alliance marches under a brittle truce toward the same gate. Above, dragons circle on wings of red flame. Whatever happens at this gate, the world will remember it.",
            portraitDisplayID = 23034,
            faction = "Horde",
            quests = {
                { id = 12500, name = "Return To Angrathar", npc = "Saurfang the Younger", faction = "Horde" },
            },
        },

        -- ----------------------------------------------------------------
        -- A time-lost flashback — see where the long road began.
        -- ----------------------------------------------------------------
        {
            chapter = "The Culling of Stratholme",
            summary = "Travel back to the hour that broke a prince — and make sure history unfolds as it always has.",
            recap = "Chromie of the Bronze Dragonflight sends you back to Stratholme, to a day history remembers in silence. The Infinite Dragonflight would rewrite this moment. Yours is the harder task: walk beside a young Prince Arthas Menethil and keep time honest, whatever price the past demands.",
            portraitDisplayID = 24877,
            quests = {
                { id = 13149, name = "Dispelling Illusions", npc = "Chromie" },
                { id = 13151, name = "A Royal Escort", npc = "Chromie" },
            },
        },

        -- ----------------------------------------------------------------
        -- Icecrown — hub-to-hub journey from the Argent Vanguard to the citadel.
        -- ----------------------------------------------------------------
        {
            chapter = "Argent Vanguard",
            summary = "Plant the Argent Crusade's banner at the rim of Icecrown and hold the line while Tirion looks north.",
            recap = "The Argent Vanguard is the last friendly ground at the southern edge of Icecrown. Crusade Commander Entari drills the new arrivals into shape. Father Gustav's engineers run the fleshbeast bombardier; Siegemaster Fezzik's jumpbot waits for one more idiot willing to take the breach. Past the tent line, the ground sours into the Valley of Echoes — and past that, Crusaders' Pinnacle, where Tirion Fordring means to draw a line the Scourge cannot cross.",
            portraitDisplayID = 31011,
            quests = {
                { id = 13036, name = "Honor Above All Else", npc = "Crusade Commander Entari" },
                { id = 13008, name = "Scourge Tactics", npc = "Crusade Commander Entari" },
                { id = 13040, name = "Curing The Incurable", npc = "Crusade Commander Entari" },
                { id = 13039, name = "Defending The Vanguard", npc = "Crusade Commander Entari" },
                { id = 13070, name = "A Cold Front Approaches", npc = "Highlord Tirion Fordring" },
                { id = 13044, name = "If There Are Survivors...", npc = "Crusader Lord Dalfors" },
                { id = 13045, name = "Into The Wild Green Yonder", npc = "Father Gustav" },
                { id = 13069, name = "Shoot 'Em Up", npc = "The Leaper" },
                { id = 13071, name = "Vile Like Fire!", npc = "Vile" },
                { id = 13086, name = "The Last Line Of Defense", npc = "Siegemaster Fezzik" },
                { id = 13104, name = "Once More Unto The Breach, Hero", npc = "Siegemaster Fezzik", faction = "Alliance" },
                { id = 13105, name = "Once More Unto The Breach, Hero", npc = "Siegemaster Fezzik", faction = "Horde" },
            },
        },
        {
            chapter = "Valley of Echoes",
            summary = "Walk north through the ruin of Scourgeholme and onto the high plateau of Crusaders' Pinnacle.",
            recap = "The Valley of Echoes is a bowl of old Scourge work. Plague altars cough smoke into the wind; restless dead pace the rim by moonlight. Father Gustav wants scourgestones. The Ebon Watcher wants the altars cold. The Argent Crusade wants the road cleared north — to the Pinnacle, where Tirion Fordring has already set his banner. When the banner flies, the whole rim of Icecrown hears it, and the gunships in the northern sky start warming their engines.",
            portraitDisplayID = 31011,
            quests = {
                { id = 13122, name = "The Scourgestone", npc = "Father Gustav" },
                { id = 13118, name = "The Purging Of Scourgeholme", npc = "Father Gustav" },
                { id = 13125, name = "The Air Stands Still", npc = "The Ebon Watcher" },
                { id = 13110, name = "The Restless Dead", npc = "The Ebon Watcher" },
                { id = 13130, name = "The Stone That Started A Revolution", npc = "The Ebon Watcher" },
                { id = 13135, name = "It Could Kill Us All", npc = "The Ebon Watcher" },
                { id = 13139, name = "Into The Frozen Heart Of Northrend", npc = "Father Gustav" },
                { id = 13141, name = "The Battle For Crusaders' Pinnacle", npc = "Crusader MacKellar" },
                { id = 13157, name = "The Crusaders' Pinnacle", npc = "Highlord Tirion Fordring" },
            },
        },
        {
            chapter = "Crusader's Pinnacle",
            summary = "Stand on the Pinnacle beside a dying paladin while the world's powers weigh his fate.",
            recap = "The Pinnacle is won. Its flagstaff flies the white hand of the Argent Crusade above the whole of southern Icecrown. But at the edge of the Fleshwerks below, Crusader Bridenbrad is dying. The plague has him. Father Gustav cannot let a hero end this way. Keeper Remulos, Alexstrasza the Life-Binder, and A'dal — three ancient powers who still remember the Light — each in turn weigh the cost. Whatever answer comes will come in its own time. Meanwhile, gryphon-riders and wyvern-masters circle the Pinnacle, waiting to lift the next wave of soldiers up to the gunships — the Skybreaker and Orgrim's Hammer — hanging over the northern gates.",
            portraitDisplayID = 31011,
            quests = {
                -- Bridenbrad
                { id = 13068, name = "A Tale of Valor", npc = "Father Gustav" },
                { id = 13072, name = "A Hero Remains", npc = "Crusader Bridenbrad" },
                { id = 13073, name = "The Keeper's Favor", npc = "Crusader Bridenbrad" },
                { id = 13074, name = "Hope Within the Emerald Nightmare", npc = "Keeper Remulos" },
                { id = 13075, name = "The Boon of Remulos", npc = "Keeper Remulos" },
                { id = 13076, name = "Time Yet Remains", npc = "Father Gustav" },
                { id = 13077, name = "The Touch of an Aspect", npc = "Crusader Bridenbrad" },
                { id = 13078, name = "Dahlia's Tear", npc = "Alexstrasza the Life-Binder" },
                { id = 13079, name = "The Boon of Alexstrasza", npc = "Alexstrasza the Life-Binder" },
                { id = 13080, name = "Hope Yet Remains", npc = "Father Gustav" },
                { id = 13081, name = "The Will of the Naaru", npc = "Crusader Bridenbrad" },
                { id = 13082, name = "The Boon of A'dal", npc = "A'dal" },
                { id = 13083, name = "Light Within the Darkness", npc = "Father Gustav" },
                -- Airship intros
                { id = 13225, name = "The Skybreaker", npc = "Marshal Ivalius", faction = "Alliance" },
                { id = 13224, name = "Orgrim's Hammer", npc = "Warlord Hork Strongbrow", faction = "Horde" },
            },
        },
        {
            chapter = "The Skybreaker",
            summary = "Ride the Alliance gunship from Ymirheim to the Broken Front to the Desolation Gate.",
            recap = "Boarding the Skybreaker is the moment Icecrown changes scale. High Captain Justin Bartlett runs the deck. Sky-Commander Keller handles the flight line. Absalan the Pious blesses every salvo. The first sortie drops into Ymirheim, where the Scourge mines its saronite. The second swings west to the Broken Front, where a Scourge vanguard once mauled the 7th Legion's first landing. After that comes the grind: Poke and Prod, Against the Giants, Coprous the Defiled, the tinker Kibli Killohertz and his lightning-based sarcasm. Farther west, past the Valley of Lost Hope, Thassarian cracks open the Desolation Gate with borrowed Scourge ordnance and a half-broken jumpbot. By the time the Skybreaker swings east again, the Guardians of Corp'rethar are already in the crosshairs.",
            portraitDisplayID = 26982,
            faction = "Alliance",
            quests = {
                -- Gunship briefings and Valley of Lost Hope tech chain
                { id = 13290, name = "Your Attention, Please", npc = "High Captain Justin Bartlett", faction = "Alliance" },
                { id = 13291, name = "Borrowed Technology", npc = "Chief Engineer Boltwrench", faction = "Alliance" },
                { id = 13292, name = "The Solution Solution", npc = "Chief Engineer Boltwrench", faction = "Alliance" },
                { id = 13383, name = "Killohertz", npc = "Kibli Killohertz", faction = "Alliance" },
                { id = 13380, name = "Leading the Charge", npc = "Tixi Wobblewrench", faction = "Alliance" },
                { id = 13381, name = "Watts My Target", npc = "Tixi Wobblewrench", faction = "Alliance" },
                { id = 13404, name = "Static Shock Troops: the Bombardment", npc = "Kibli Killohertz", faction = "Alliance" },
                { id = 13382, name = "Putting the Hertz: The Valley of Lost Hope", npc = "Kibli Killohertz", faction = "Alliance" },
                -- Ymirheim assault
                { id = 13296, name = "Get to Ymirheim!", npc = "Aerial Commander Seyton", faction = "Alliance" },
                { id = 13280, name = "King of the Mountain", npc = "Frazzle Geargrinder", faction = "Alliance" },
                { id = 13341, name = "Joining the Assault", npc = "Knight-Captain Drosche", faction = "Alliance" },
                { id = 13309, name = "Assault by Air", npc = "Ground Commander Koup", faction = "Alliance" },
                { id = 13284, name = "Assault by Ground", npc = "Skybreaker Squad Leader", faction = "Alliance" },
                { id = 13300, name = "Slaves to Saronite", npc = "Absalan the Pious", faction = "Alliance" },
                { id = 13336, name = "Blood of the Chosen", npc = "Knight-Captain Drosche", faction = "Alliance" },
                -- Broken Front
                { id = 13227, name = "Judgment Day Comes!", npc = "Absalan the Pious", faction = "Alliance" },
                { id = 13231, name = "The Broken Front", npc = "High Captain Justin Bartlett", faction = "Alliance" },
                { id = 13232, name = "Finish Me!", npc = "Dying Footman", faction = "Alliance" },
                { id = 13233, name = "No Mercy!", npc = "High Captain Justin Bartlett", faction = "Alliance" },
                -- Poke and Prod cleanup
                { id = 13287, name = "Poke and Prod", npc = "Thassarian", faction = "Alliance" },
                { id = 13288, name = "That's Abominable!", npc = "Thassarian", faction = "Alliance" },
                { id = 13294, name = "Against the Giants", npc = "Thassarian", faction = "Alliance" },
                { id = 13298, name = "Coprous the Defiled", npc = "Thassarian", faction = "Alliance" },
                { id = 13295, name = "Basic Chemistry", npc = "Chief Engineer Boltwrench", faction = "Alliance" },
                { id = 13238, name = "Good For Something?", npc = "High Captain Justin Bartlett", faction = "Alliance" },
                -- Aldur'thar: The Desolation Gate
                { id = 13318, name = "Drag and Drop", npc = "Thassarian", faction = "Alliance" },
                { id = 13319, name = "Drag and Drop", npc = "Thassarian", faction = "Alliance" },
                { id = 13354, name = "Chain of Command", npc = "Thassarian", faction = "Alliance" },
                { id = 13357, name = "Retest Now", npc = "Thassarian", faction = "Alliance" },
                { id = 13358, name = "Not a Bug", npc = "Thassarian", faction = "Alliance" },
                { id = 13366, name = "Need More Info", npc = "Thassarian", faction = "Alliance" },
                { id = 13346, name = "No Rest For The Wicked", npc = "Thassarian", faction = "Alliance" },
                -- Corp'rethar
                { id = 13338, name = "The Guardians of Corp'rethar", npc = "Thassarian", faction = "Alliance" },
            },
        },
        {
            chapter = "Orgrim's Hammer",
            summary = "Ride the Horde gunship from Ymirheim to the Broken Front to the Desolation Gate.",
            recap = "Orgrim's Hammer is Warchief Garrosh's answer to the Skybreaker — a Horde gunship with a bone to pick. Sky-Reaver Korm Blackscar runs the deck. Sky-Commander Ichman flies the line. Brother Keltan blesses the cannons. The first sortie drops into Ymirheim, where the Scourge mines its saronite. The second swings west to the Broken Front, where a Horde column was hit broadside and left scattered. After that comes the grind: Poke and Prod, Against the Giants, Coprous the Defiled, the goblin Nargle Lashcord and his Fringe Engineer Tezzla. Farther west, past the Valley of Lost Hope, Koltira Deathweaver pries the Desolation Gate open with bent Scourge gear and colder patience. By the time Orgrim's Hammer swings east, the Guardians of Corp'rethar are already bleeding.",
            portraitDisplayID = 27336,
            faction = "Horde",
            quests = {
                -- Gunship briefings and Valley of Lost Hope tech chain
                { id = 13261, name = "Volatility", npc = "Chief Engineer Copperclaw", faction = "Horde" },
                { id = 13373, name = "Fringe Science Benefits", npc = "Nargle Lashcord", faction = "Horde" },
                { id = 13374, name = "Amped for Revolt!", npc = "Nargle Lashcord", faction = "Horde" },
                { id = 13376, name = "Total Ohmage: The Valley of Lost Hope!", npc = "Nargle Lashcord", faction = "Horde" },
                { id = 13379, name = "Green Technology", npc = "Nargle Lashcord", faction = "Horde" },
                { id = 13406, name = "Riding the Wavelength: The Bombardment", npc = "Nargle Lashcord", faction = "Horde" },
                -- Ymirheim assault
                { id = 13293, name = "Get to Ymirheim!", npc = "Aerial Commander Attumen", faction = "Horde" },
                { id = 13283, name = "King of the Mountain", npc = "Blast Thunderbomb", faction = "Horde" },
                { id = 13340, name = "Joining the Assault", npc = "Warbringer Davos Rioht", faction = "Horde" },
                { id = 13310, name = "Assault by Air", npc = "Ground Commander Xutjja", faction = "Horde" },
                { id = 13301, name = "Assault by Ground", npc = "Kor'kron Squad Leader", faction = "Horde" },
                { id = 13302, name = "Slaves to Saronite", npc = "Brother Keltan", faction = "Horde" },
                { id = 13330, name = "Blood of the Chosen", npc = "Warbringer Davos Rioht", faction = "Horde" },
                -- Broken Front
                { id = 13226, name = "Judgment Day Comes!", npc = "Brother Keltan", faction = "Horde" },
                { id = 13228, name = "The Broken Front", npc = "Sky-Reaver Korm Blackscar", faction = "Horde" },
                { id = 13230, name = "Avenge Me!", npc = "Dying Berserker", faction = "Horde" },
                { id = 13234, name = "Make Them Pay!", npc = "Sky-Reaver Korm Blackscar", faction = "Horde" },
                -- Poke and Prod cleanup
                { id = 13237, name = "Poke and Prod", npc = "Koltira Deathweaver", faction = "Horde" },
                { id = 13264, name = "That's Abominable!", npc = "Koltira Deathweaver", faction = "Horde" },
                { id = 13277, name = "Against the Giants", npc = "Koltira Deathweaver", faction = "Horde" },
                { id = 13278, name = "Coprous the Defiled", npc = "Koltira Deathweaver", faction = "Horde" },
                { id = 13279, name = "Basic Chemistry", npc = "Chief Engineer Copperclaw", faction = "Horde" },
                { id = 13260, name = "Takes One to Know One", npc = "Sky-Reaver Korm Blackscar", faction = "Horde" },
                -- Aldur'thar: The Desolation Gate
                { id = 13352, name = "Drag and Drop", npc = "Koltira Deathweaver", faction = "Horde" },
                { id = 13353, name = "Drag and Drop", npc = "Koltira Deathweaver", faction = "Horde" },
                { id = 13355, name = "Cannot Reproduce", npc = "Koltira Deathweaver", faction = "Horde" },
                { id = 13356, name = "Retest Now", npc = "Koltira Deathweaver", faction = "Horde" },
                { id = 13365, name = "Not a Bug", npc = "Koltira Deathweaver", faction = "Horde" },
                { id = 13351, name = "Sneak Preview", npc = "Koltira Deathweaver", faction = "Horde" },
                { id = 13367, name = "No Rest For The Wicked", npc = "Koltira Deathweaver", faction = "Horde" },
                -- Corp'rethar
                { id = 13316, name = "The Guardians of Corp'rethar", npc = "Koltira Deathweaver", faction = "Horde" },
            },
        },
        {
            chapter = "Saronite Mines",
            summary = "Walk the saronite tunnels below Ymirheim and test what the whispers can do to a soldier's mind.",
            recap = "The saronite mines beneath Ymirheim are not just a supply line. They are something older, colder, and hungrier than any ore vein on Azeroth. The metal whispers. Miners chained to the walls hear their names called by voices they once loved. The Argent Crusade has quiet questions about what prolonged exposure does to a living mind. The answers do not make it out of the tunnels.",
            portraitDisplayID = 28164,
            quests = {
                { id = 13308, name = "Mind Tricks", npc = "Darkspeaker R'khem" },
            },
        },
        {
            chapter = "The Shadow Vault",
            summary = "Dress in Scarlet cloth, take the Vault for the Ebon Blade, and ride up to Malykriss to kill four riders.",
            recap = "The Scarlet Onslaught has buried itself in the black ice of western Icecrown. The fortress is called the Shadow Vault. High Abbot Landgren commands it now. The Ebon Blade's plan is ugly — wear the Scarlet's own colors, pray nobody looks twice, and open every door from the inside. When the Vault falls, Baron Sliver holds court in its upper halls. Vereth the Cunning sketches the roads out in blood. The Lich King's saronite quarries are pried open. Above the Vault, the flying necropolis of Malykriss still hangs, with four riders of the Bloodbane order riding out the apocalypse in miniature: one of the Unholy, one of Frost, one of Blood, and the name that binds them.",
            portraitDisplayID = 28407,
            quests = {
                -- Entering the Vault in Scarlet colors
                { id = 12887, name = "It's All Fun and Games", npc = "Talbot", faction = "Alliance" },
                { id = 12892, name = "It's All Fun and Games", npc = "Talbot", faction = "Horde" },
                { id = 12891, name = "I Have an Idea, But First...", npc = "Crusader Bridenbrad" },
                { id = 12893, name = "Free Your Mind", npc = "Crusader Bridenbrad" },
                { id = 12896, name = "If He Cannot Be Turned", npc = "Crusader Bridenbrad", faction = "Alliance" },
                { id = 12897, name = "If He Cannot Be Turned", npc = "Crusader Bridenbrad", faction = "Horde" },
                { id = 12898, name = "The Shadow Vault", npc = "High Abbot Landgren", faction = "Alliance" },
                { id = 12899, name = "The Shadow Vault", npc = "High Abbot Landgren", faction = "Horde" },
                -- Baron Sliver's reign
                { id = 12995, name = "Leave Our Mark", npc = "Baron Sliver" },
                { id = 12938, name = "The Duke", npc = "Baron Sliver" },
                { id = 12939, name = "Honor Challenge", npc = "Baron Sliver" },
                { id = 12943, name = "Shadow Vault Decree", npc = "Baron Sliver" },
                { id = 12949, name = "Get the Key", npc = "Baron Sliver" },
                { id = 12951, name = "Let the Baron Know", npc = "Baron Sliver" },
                -- Malykriss bridge
                { id = 13145, name = "The Vile Hold", npc = "Vereth the Cunning" },
                { id = 13174, name = "Amidst the Confusion", npc = "Vereth the Cunning" },
                { id = 13143, name = "New Recruit", npc = "Vereth the Cunning" },
                -- Malykriss — the four riders
                { id = 13155, name = "Vereth the Cunning", npc = "Vereth the Cunning" },
                { id = 13161, name = "The Rider of the Unholy", npc = "Vereth the Cunning" },
                { id = 13162, name = "The Rider of Frost", npc = "Vereth the Cunning" },
                { id = 13163, name = "The Rider of Blood", npc = "Vereth the Cunning" },
                { id = 13164, name = "The Fate of Bloodbane", npc = "Vereth the Cunning" },
                { id = 13171, name = "From Whence They Came", npc = "Vereth the Cunning" },
                { id = 13172, name = "Seeds of Chaos", npc = "Vereth the Cunning" },
                -- Keritose Bloodblade and Lady Nightswood
                { id = 13146, name = "Generosity Abounds", npc = "Lady Nightswood" },
                { id = 13147, name = "Matchmaker", npc = "Lady Nightswood" },
                { id = 13160, name = "Stunning View", npc = "Keritose Bloodblade" },
                { id = 13168, name = "Parting Gifts", npc = "Keritose Bloodblade" },
                { id = 13169, name = "An Undead's Best Friend", npc = "Keritose Bloodblade" },
                { id = 13170, name = "Honor is for the Weak", npc = "Keritose Bloodblade" },
            },
        },
        {
            chapter = "Blackwatch",
            summary = "Burn Doctor Olakin Sainrith's plague lab, save Father Kamaros's people, and finish the Runesmiths' work.",
            recap = "South of the Pinnacle, past the rim of the Valley of Echoes, a little Scarlet outpost called Blackwatch keeps quiet company with the Scourge it claims to hate. The Argent Crusade has questions about that. Grimly wants the plague altars in pieces. Father Kamaros, somehow still alive, has a list of his own wounded. Doctor Olakin Sainrith is busy inside the lab cooking something that was never meant to breathe. Overhead, the Flesh Giant Champion walks the ice. Inside Malykriss's foundry, the Runesmiths still pound the Scourge's armor — and one old vrykul skeleton is about to do more work dead than it ever did alive.",
            portraitDisplayID = 26608,
            quests = {
                { id = 13106, name = "Blackwatch", npc = "Crusader MacKellar" },
                { id = 13117, name = "Where Are They Coming From?", npc = "Grimly" },
                { id = 13119, name = "Destroying the Altars", npc = "Grimly" },
                { id = 13120, name = "Death's Gaze", npc = "Grimly" },
                { id = 13134, name = "Spill Their Blood", npc = "Grimly" },
                { id = 13136, name = "Jagged Shards", npc = "Grimly" },
                { id = 13138, name = "I'm Smelting... Smelting!", npc = "Grimly" },
                { id = 13152, name = "A Visit to the Doctor", npc = "Grimly" },
                { id = 13211, name = "By Fire Be Purged", npc = "Olakin Sainrith" },
                { id = 13212, name = "He's Gone to Pieces", npc = "Olakin Sainrith" },
                { id = 13220, name = "Putting Olakin Back Together Again", npc = "Olakin Sainrith" },
                { id = 13235, name = "The Flesh Giant Champion", npc = "Darkrider Arly" },
                { id = 13229, name = "I'm Not Dead Yet!", npc = "Father Kamaros" },
                { id = 13221, name = "I'm Not Dead Yet!", npc = "Father Kamaros" },
                { id = 13140, name = "The Runesmiths of Malykriss", npc = "Vereth the Cunning" },
                { id = 13144, name = "Killing Two Scourge With One Skeleton", npc = "Vereth the Cunning" },
            },
        },
        {
            chapter = "Jotunheim",
            summary = "Put on vrykul skin, fight through Valhalas's trials, and pay a Bone Witch's debt in blood.",
            recap = "Past the Argent line, the Ebon Blade works in cruder tools. Uzo Deathcaller keeps a pen of vrykul prisoners the Crusade cannot know about. Bragi the Mad waits at Jotunheim with a grudge, a list of vargul he wants back, and an increasingly unhinged plan for their recovery. The Bone Witch sells her favors in bones. And at Valhalas, the vrykul hold court for the worthy dead — which means admission, for the right kind of monster, can be earned. Read the bones. Kill the water terror. Find the ancient hero. Win the challenge rounds. Put on their skin. Walk out over their corpses. By the time the hall goes quiet, the Ebon Blade has one last errand — a banshee's revenge, and a Duke who needs his competition eliminated.",
            portraitDisplayID = 26608,
            quests = {
                -- Uzo's off-books work
                { id = 12982, name = "Ebon Blade Prisoners", npc = "Uzo Deathcaller" },
                { id = 12992, name = "Crush Dem Vrykuls!", npc = "Crusader Jonathan" },
                { id = 12999, name = "The Bone Witch", npc = "Uzo Deathcaller" },
                -- Bragi at Jotunheim
                { id = 13059, name = "Revenge for the Vargul", npc = "Bragi" },
                { id = 13084, name = "Vandalizing Jotunheim", npc = "Bragi" },
                { id = 13085, name = "Vaelen Has Returned", npc = "Bragi" },
                { id = 13092, name = "Reading the Bones", npc = "Bragi", faction = "Alliance" },
                { id = 13093, name = "Reading the Bones", npc = "Bragi", faction = "Horde" },
                { id = 13042, name = "Deep in the Bowels of The Underhalls", npc = "Bragi" },
                { id = 13043, name = "The Sum is Greater than the Parts", npc = "Bragi" },
                { id = 13091, name = "The Art of Being a Water Terror", npc = "Bragi" },
                { id = 13121, name = "Through the Eye", npc = "Bragi" },
                { id = 13133, name = "Find the Ancient Hero", npc = "Bragi" },
                { id = 13137, name = "Not-So-Honorable Combat", npc = "Bragi" },
                -- Valhalas trials
                { id = 13213, name = "Battle at Valhalas", npc = "Geirrvif" },
                { id = 13214, name = "Battle at Valhalas: Fallen Heroes", npc = "Geirrvif" },
                { id = 13215, name = "Battle at Valhalas: Khit'rix the Dark Master", npc = "Geirrvif" },
                { id = 13216, name = "Battle at Valhalas: The Return of Sigrid Iceborn", npc = "Geirrvif" },
                { id = 13217, name = "Battle at Valhalas: Carnage!", npc = "Geirrvif" },
                { id = 13218, name = "Battle at Valhalas: Thane Deathblow", npc = "Geirrvif" },
                { id = 13219, name = "Battle at Valhalas: Final Challenge", npc = "Geirrvif" },
                -- Ebon Blade errands
                { id = 12955, name = "Eliminate the Competition", npc = "Baron Sliver" },
                { id = 13142, name = "Banshee's Revenge", npc = "Vereth the Cunning" },
            },
        },
        {
            chapter = "Icecrown Citadel",
            summary = "Bomb the saronite pits beneath Sindragosa's Fall and shake the citadel's gates from within.",
            recap = "The citadel's gates are not for hammering. Sergeant Stackhammer knows it. Sergeant Kregga knows it. The Alliance and Horde sappers have quieter work — crawl into the saronite pits beneath Sindragosa's Fall and set the charges that will shake the foundations from below. Before the pits go up, a voice begins to whisper out of the saronite dark. Whoever he is, he knows a name. He wants it spoken. He wants you to come back when the dust settles and hear the rest of his story at the First Legion Forward Camp.",
            portraitDisplayID = 30686,
            quests = {
                -- Alliance charges
                { id = 13386, name = "Exploiting an Opening", npc = "Sergeant Stackhammer", faction = "Alliance" },
                { id = 13387, name = "Securing the Perimeter", npc = "Sergeant Stackhammer", faction = "Alliance" },
                { id = 13388, name = "Set it Off!", npc = "Sergeant Stackhammer", faction = "Alliance" },
                -- Horde charges
                { id = 13258, name = "Opportunity", npc = "Sergeant Kregga", faction = "Horde" },
                { id = 13259, name = "Establishing Superiority", npc = "Sergeant Kregga", faction = "Horde" },
                { id = 13262, name = "Blow it Up!", npc = "Sergeant Kregga", faction = "Horde" },
                -- Matthias Lehner's voice in the dark
                { id = 13390, name = "A Voice in the Dark", npc = "Matthias Lehner", faction = "Alliance" },
                { id = 13271, name = "A Voice in the Dark", npc = "Matthias Lehner", faction = "Horde" },
                { id = 13391, name = "Time to Hide", npc = "Matthias Lehner", faction = "Alliance" },
                { id = 13275, name = "Time to Hide", npc = "Matthias Lehner", faction = "Horde" },
                { id = 13392, name = "Return to the Surface", npc = "Matthias Lehner", faction = "Alliance" },
                { id = 13282, name = "Return to the Surface", npc = "Matthias Lehner", faction = "Horde" },
            },
        },
        {
            chapter = "First Legion Forward Camp",
            summary = "Pitch camp in the lee of Sindragosa's fall and read the Lich King's ledger of ruin.",
            recap = "Forward Camp is the last flat ground on the way to the citadel. Sappers finish what the bomb chain started. Sky-Commander Keller and Sky-Commander Ichman land their gunship crews to patch what the bombing shook loose. Matthias Lehner, the voice from the saronite pits, begins to speak plainly — and sends you into the Army of the Damned, into the wreckage beneath Sindragosa's broken hill, and into the futility of a hero's last charge. Everything he shows you has the shape of a confession.",
            portraitDisplayID = 27522,
            quests = {
                -- Field repairs
                { id = 13393, name = "Field Repairs", npc = "Sky-Commander Keller", faction = "Alliance" },
                { id = 13304, name = "Field Repairs", npc = "Sky-Commander Ichman", faction = "Horde" },
                { id = 13389, name = "A Short Fuse", npc = "Sergeant Stackhammer", faction = "Alliance" },
                { id = 13263, name = "A Short Fuse", npc = "Sergeant Kregga", faction = "Horde" },
                -- Matthias Lehner's memories (opening)
                { id = 13394, name = "Do Your Worst", npc = "Matthias Lehner", faction = "Alliance" },
                { id = 13305, name = "Do Your Worst", npc = "Matthias Lehner", faction = "Horde" },
                { id = 13395, name = "Army of the Damned", npc = "Matthias Lehner", faction = "Alliance" },
                { id = 13236, name = "Army of the Damned", npc = "Matthias Lehner", faction = "Horde" },
                { id = 13348, name = "Futility", npc = "Thassarian", faction = "Alliance" },
                { id = 13396, name = "Futility", npc = "Koltira Deathweaver", faction = "Horde" },
                -- Sindragosa's fall / cradle of the frostbrood
                { id = 13397, name = "Sindragosa's Fall", npc = "Sky-Commander Keller", faction = "Alliance" },
                { id = 13349, name = "Cradle of the Frostbrood", npc = "Sky-Commander Ichman", faction = "Horde" },
            },
        },
        {
            chapter = "Sindragosa's Fall",
            summary = "Follow Matthias Lehner through Arthas' own memories to the foot of the citadel and Tirion's final gambit.",
            recap = "The voice in the dark has a name now — Matthias Lehner. He claims to know the Lich King better than any living thing should. His memories run like a buried river through the Frozen Wastes. He leads you to a dragon's corpse. To a hunter and a prince. To the knowledge that cannot be unknown. Whether he can be trusted is a judgement you will make when the road ends — at the foot of the citadel, where Tirion Fordring lifts the Ashbringer and calls for one more charge.",
            portraitDisplayID = 27522,
            quests = {
                { id = 13398, name = "Where Dragons Fell", npc = "Matthias Lehner", faction = "Alliance" },
                { id = 13359, name = "Where Dragons Fell", npc = "Matthias Lehner", faction = "Horde" },
                { id = 13399, name = "Time for Answers", npc = "Matthias Lehner", faction = "Alliance" },
                { id = 13360, name = "Time for Answers", npc = "Matthias Lehner", faction = "Horde" },
                { id = 13400, name = "The Hunter and the Prince", npc = "Matthias Lehner", faction = "Alliance" },
                { id = 13361, name = "The Hunter and the Prince", npc = "Matthias Lehner", faction = "Horde" },
                { id = 13401, name = "Knowledge is a Terrible Burden", npc = "Thassarian", faction = "Alliance" },
                { id = 13362, name = "Knowledge is a Terrible Burden", npc = "Koltira Deathweaver", faction = "Horde" },
                { id = 13402, name = "Tirion's Help", npc = "Thassarian", faction = "Alliance" },
                { id = 13363, name = "Argent Aid", npc = "Koltira Deathweaver", faction = "Horde" },
                { id = 13403, name = "Tirion's Gambit", npc = "Highlord Tirion Fordring", faction = "Alliance" },
                { id = 13364, name = "Tirion's Gambit", npc = "Highlord Tirion Fordring", faction = "Horde" },
            },
        },

        -- ----------------------------------------------------------------
        -- Endgame — under the citadel, then into it.
        -- ----------------------------------------------------------------
        {
            chapter = "The Frozen Halls",
            summary = "Lead a covert strike beneath Icecrown Citadel, closer to Frostmourne than any living hand has come.",
            recap = "Lady Jaina Proudmoore — or Lady Sylvanas Windrunner, if you ride under a darker banner — has found a door. Not a welcome one. A seam in the citadel's foundation, wide enough for a small party willing to see what they should not. Through the Forge of Souls. Through the Pit of Saron. Into the Halls of Reflection, where something waits that has been waiting a long time.",
            portraitDisplayID = 30696,
            quests = {
                { id = 24510, name = "Inside the Frozen Citadel", npc = "Apprentice Nelphi", faction = "Alliance" },
                { id = 24506, name = "Inside the Frozen Citadel", npc = "Dark Ranger Vorel", faction = "Horde" },
                { id = 24499, name = "Echoes of Tortured Souls", npc = "Lady Jaina Proudmoore", faction = "Alliance" },
                { id = 24511, name = "Echoes of Tortured Souls", npc = "Lady Sylvanas Windrunner", faction = "Horde" },
                { id = 24683, name = "The Pit of Saron", npc = "Lady Jaina Proudmoore", faction = "Alliance" },
                { id = 24682, name = "The Pit of Saron", npc = "Lady Sylvanas Windrunner", faction = "Horde" },
                { id = 24710, name = "Deliverance from the Pit", npc = "Martin Victus", faction = "Alliance" },
                { id = 24712, name = "Deliverance from the Pit", npc = "Gorkun Ironskull", faction = "Horde" },
                { id = 24711, name = "Frostmourne", npc = "Lady Jaina Proudmoore", faction = "Alliance" },
                { id = 24713, name = "Frostmourne", npc = "Lady Sylvanas Windrunner", faction = "Horde" },
            },
        },
        {
            chapter = "Fall of the Lich King",
            achievementID = 4608,
            summary = "Climb the spire of Icecrown Citadel and write the last page of Arthas Menethil's story.",
            recap = "Above the ice, at the roof of the world, the Frozen Throne waits. The Ashen Verdict — Argent Crusade and Ebon Blade, bound by a single purpose — stands at the citadel's door. Highlord Tirion Fordring lifts the Ashbringer. Every victory in Northrend, every fallen soldier, every mile of ground bought in blood has led here. One way or another, the reign of Arthas Menethil ends at the summit.",
            portraitDisplayID = 31011,
            quests = {},
        },
    },
}
