local addonName, SM = ...

local ICECROWN_QUEST_NAMES = {
    [12806] = "To the Rise with all Due Haste!",
    [12807] = "The Story Thus Far...",
    [12810] = "Blood in the Water",
    [12813] = "From Their Corpses, Rise!",
    [12814] = "You'll Need a Gryphon",
    [12815] = "No Fly Zone",
    [12838] = "Intelligence Gathering",
    [12839] = "The Grand (Admiral's) Plan",
    [12840] = "In Strict Confidence",
    [12847] = "Second Chances",
    [12852] = "The Admiral Revealed",
    [12887] = "It's All Fun and Games",
    [12891] = "I Have an Idea, But First...",
    [12892] = "It's All Fun and Games",
    [12893] = "Free Your Mind",
    [12896] = "If He Cannot Be Turned",
    [12897] = "If He Cannot Be Turned",
    [12898] = "The Shadow Vault",
    [12899] = "The Shadow Vault",
    [12938] = "The Duke",
    [12939] = "Honor Challenge",
    [12943] = "Shadow Vault Decree",
    [12949] = "Get the Key",
    [12951] = "Let the Baron Know",
    [12955] = "Eliminate the Competition",
    [12982] = "Ebon Blade Prisoners",
    [12992] = "Crush Dem Vrykuls!",
    [12995] = "Leave Our Mark",
    [12999] = "The Bone Witch",
    [13008] = "Scourge Tactics",
    [13036] = "Honor Above All Else",
    [13039] = "Defending The Vanguard",
    [13040] = "Curing The Incurable",
    [13042] = "Deep in the Bowels of The Underhalls",
    [13043] = "The Sum is Greater than the Parts",
    [13044] = "If There Are Survivors...",
    [13045] = "Into The Wild Green Yonder",
    [13059] = "Revenge for the Vargul",
    [13068] = "A Tale of Valor",
    [13069] = "Shoot 'Em Up",
    [13070] = "A Cold Front Approaches",
    [13071] = "Vile Like Fire!",
    [13072] = "A Hero Remains",
    [13073] = "The Keeper's Favor",
    [13075] = "The Boon of Remulos",
    [13076] = "Time Yet Remains",
    [13077] = "The Touch of an Aspect",
    [13079] = "The Boon of Alexstrasza",
    [13080] = "Hope Yet Remains",
    [13081] = "The Will of the Naaru",
    [13082] = "The Boon of A'dal",
    [13083] = "Light Within the Darkness",
    [13084] = "Vandalizing Jotunheim",
    [13085] = "Vaelen Has Returned",
    [13086] = "The Last Line Of Defense",
    [13091] = "The Art of Being a Water Terror",
    [13092] = "Reading the Bones",
    [13093] = "Reading the Bones",
    [13104] = "Once More Unto The Breach, Hero",
    [13105] = "Once More Unto The Breach, Hero",
    [13106] = "Blackwatch",
    [13110] = "The Restless Dead",
    [13117] = "Where Are They Coming From?",
    [13118] = "The Purging Of Scourgeholme",
    [13119] = "Destroying the Altars",
    [13120] = "Death's Gaze",
    [13121] = "Through the Eye",
    [13122] = "The Scourgestone",
    [13125] = "The Air Stands Still",
    [13130] = "The Stone That Started A Revolution",
    [13133] = "Find the Ancient Hero",
    [13134] = "Spill Their Blood",
    [13135] = "It Could Kill Us All",
    [13136] = "Jagged Shards",
    [13137] = "Not-So-Honorable Combat",
    [13138] = "I'm Smelting... Smelting!",
    [13139] = "Into The Frozen Heart Of Northrend",
    [13140] = "The Runesmiths of Malykriss",
    [13141] = "The Battle For Crusaders' Pinnacle",
    [13142] = "Banshee's Revenge",
    [13143] = "New Recruit",
    [13144] = "Killing Two Scourge With One Skeleton",
    [13145] = "The Vile Hold",
    [13146] = "Generosity Abounds",
    [13147] = "Matchmaker",
    [13152] = "A Visit to the Doctor",
    [13155] = "Vereth the Cunning",
    [13157] = "The Crusaders' Pinnacle",
    [13160] = "Stunning View",
    [13161] = "The Rider of the Unholy",
    [13162] = "The Rider of Frost",
    [13163] = "The Rider of Blood",
    [13164] = "The Fate of Bloodbane",
    [13168] = "Parting Gifts",
    [13169] = "An Undead's Best Friend",
    [13170] = "Honor is for the Weak",
    [13171] = "From Whence They Came",
    [13172] = "Seeds of Chaos",
    [13174] = "Amidst the Confusion",
    [13211] = "By Fire Be Purged",
    [13212] = "He's Gone to Pieces",
    [13213] = "Battle at Valhalas",
    [13214] = "Battle at Valhalas: Fallen Heroes",
    [13215] = "Battle at Valhalas: Khit'rix the Dark Master",
    [13216] = "Battle at Valhalas: The Return of Sigrid Iceborn",
    [13217] = "Battle at Valhalas: Carnage!",
    [13218] = "Battle at Valhalas: Thane Deathblow",
    [13219] = "Battle at Valhalas: Final Challenge",
    [13220] = "Putting Olakin Back Together Again",
    [13221] = "I'm Not Dead Yet!",
    [13224] = "Orgrim's Hammer",
    [13225] = "The Skybreaker",
    [13226] = "Judgment Day Comes!",
    [13227] = "Judgment Day Comes!",
    [13229] = "I'm Not Dead Yet!",
    [13230] = "Avenge Me!",
    [13232] = "Finish Me!",
    [13235] = "The Flesh Giant Champion",
    [13236] = "Army of the Damned",
    [13258] = "Opportunity",
    [13259] = "Establishing Superiority",
    [13262] = "Blow it Up!",
    [13263] = "A Short Fuse",
    [13271] = "A Voice in the Dark",
    [13275] = "Time to Hide",
    [13280] = "King of the Mountain",
    [13282] = "Return to the Surface",
    [13283] = "King of the Mountain",
    [13284] = "Assault by Ground",
    [13293] = "Get to Ymirheim!",
    [13296] = "Get to Ymirheim!",
    [13301] = "Assault by Ground",
    [13304] = "Field Repairs",
    [13305] = "Do Your Worst",
    [13308] = "Mind Tricks",
    [13309] = "Assault by Air",
    [13310] = "Assault by Air",
    [13340] = "Joining the Assault",
    [13341] = "Joining the Assault",
    [13348] = "Futility",
    [13359] = "Where Dragons Fell",
    [13360] = "Time for Answers",
    [13361] = "The Hunter and the Prince",
    [13362] = "Knowledge is a Terrible Burden",
    [13363] = "Argent Aid",
    [13364] = "Tirion's Gambit",
    [13373] = "Fringe Science Benefits",
    [13374] = "Amped for Revolt!",
    [13376] = "Total Ohmage: The Valley of Lost Hope!",
    [13379] = "Green Technology",
    [13380] = "Leading the Charge",
    [13381] = "Watts My Target",
    [13382] = "Putting the Hertz: The Valley of Lost Hope",
    [13383] = "Killohertz",
    [13386] = "Exploiting an Opening",
    [13387] = "Securing the Perimeter",
    [13388] = "Set it Off!",
    [13389] = "A Short Fuse",
    [13390] = "A Voice in the Dark",
    [13391] = "Time to Hide",
    [13392] = "Return to the Surface",
    [13393] = "Field Repairs",
    [13394] = "Do Your Worst",
    [13395] = "Army of the Damned",
    [13396] = "Futility",
    [13398] = "Where Dragons Fell",
    [13399] = "Time for Answers",
    [13400] = "The Hunter and the Prince",
    [13401] = "Knowledge is a Terrible Burden",
    [13402] = "Tirion's Help",
    [13403] = "Tirion's Gambit",
    [13404] = "Static Shock Troops: the Bombardment",
    [13406] = "Riding the Wavelength: The Bombardment",
    [13481] = "Let's Get Out of Here!",
    [13482] = "Let's Get Out of Here",
    [13592] = "A Valiant's Field Training",
    [13593] = "Valiant Of Stormwind",
    [13600] = "A Worthy Weapon",
    [13603] = "A Blade Fit For A Champion",
    [13616] = "The Edge Of Winter",
    [13625] = "Learning The Reins",
    [13633] = "The Black Knight of Westfall?",
    [13634] = "The Black Knight of Silverpine?",
    [13641] = "The Seer's Crystal",
    [13643] = "The Stories Dead Men Tell",
    [13654] = "There's Something About the Squire",
    [13663] = "The Black Knight's Orders",
    [13664] = "The Black Knight's Fall",
    [13665] = "The Grand Melee",
    [13666] = "A Blade Fit For A Champion",
    [13667] = "The Argent Tournament",
    [13668] = "The Argent Tournament",
    [13669] = "A Worthy Weapon",
    [13670] = "The Edge Of Winter",
    [13671] = "Training In The Field",
    [13672] = "Up To The Challenge",
    [13673] = "A Blade Fit For A Champion",
    [13674] = "A Worthy Weapon",
    [13675] = "The Edge Of Winter",
    [13676] = "Training In The Field",
    [13677] = "Learning The Reins",
    [13678] = "Up To The Challenge",
    [13679] = "The Aspirant's Challenge",
    [13680] = "The Aspirant's Challenge",
    [13682] = "Threat From Above",
    [13684] = "A Valiant Of Stormwind",
    [13685] = "A Valiant Of Ironforge",
    [13688] = "A Valiant Of Gnomeregan",
    [13689] = "A Valiant Of Darnassus",
    [13690] = "A Valiant Of The Exodar",
    [13691] = "A Valiant Of Orgrimmar",
    [13693] = "A Valiant Of Sen'jin",
    [13694] = "A Valiant Of Thunder Bluff",
    [13695] = "A Valiant Of Undercity",
    [13696] = "A Valiant Of Silvermoon",
    [13697] = "The Valiant's Charge",
    [13699] = "The Valiant's Challenge",
    [13702] = "A Champion Rises",
    [13703] = "Valiant Of Ironforge",
    [13704] = "Valiant Of Gnomeregan",
    [13705] = "Valiant Of The Exodar",
    [13706] = "Valiant Of Darnassus",
    [13707] = "Valiant Of Orgrimmar",
    [13708] = "Valiant Of Sen'jin",
    [13709] = "Valiant Of Thunder Bluff",
    [13710] = "Valiant Of Undercity",
    [13711] = "Valiant Of Silvermoon",
    [13713] = "The Valiant's Challenge",
    [13714] = "The Valiant's Charge",
    [13715] = "The Valiant's Charge",
    [13716] = "The Valiant's Charge",
    [13717] = "The Valiant's Charge",
    [13718] = "The Valiant's Charge",
    [13719] = "The Valiant's Charge",
    [13720] = "The Valiant's Charge",
    [13721] = "The Valiant's Charge",
    [13722] = "The Valiant's Charge",
    [13723] = "The Valiant's Challenge",
    [13724] = "The Valiant's Challenge",
    [13725] = "The Valiant's Challenge",
    [13726] = "The Valiant's Challenge",
    [13727] = "The Valiant's Challenge",
    [13728] = "The Valiant's Challenge",
    [13729] = "The Valiant's Challenge",
    [13731] = "The Valiant's Challenge",
    [13732] = "A Champion Rises",
    [13733] = "A Champion Rises",
    [13734] = "A Champion Rises",
    [13735] = "A Champion Rises",
    [13736] = "A Champion Rises",
    [13737] = "A Champion Rises",
    [13738] = "A Champion Rises",
    [13739] = "A Champion Rises",
    [13740] = "A Champion Rises",
    [13741] = "A Blade Fit For A Champion",
    [13742] = "A Worthy Weapon",
    [13743] = "The Edge Of Winter",
    [13744] = "A Valiant's Field Training",
    [13745] = "The Grand Melee",
    [13746] = "A Blade Fit For A Champion",
    [13747] = "A Worthy Weapon",
    [13748] = "The Edge Of Winter",
    [13749] = "A Valiant's Field Training",
    [13750] = "The Grand Melee",
    [13752] = "A Blade Fit For A Champion",
    [13753] = "A Worthy Weapon",
    [13754] = "The Edge Of Winter",
    [13755] = "A Valiant's Field Training",
    [13756] = "The Grand Melee",
    [13757] = "A Blade Fit For A Champion",
    [13758] = "A Worthy Weapon",
    [13759] = "The Edge Of Winter",
    [13760] = "A Valiant's Field Training",
    [13761] = "The Grand Melee",
    [13762] = "A Blade Fit For A Champion",
    [13763] = "A Worthy Weapon",
    [13764] = "The Edge Of Winter",
    [13765] = "A Valiant's Field Training",
    [13767] = "The Grand Melee",
    [13768] = "A Blade Fit For A Champion",
    [13769] = "A Worthy Weapon",
    [13770] = "The Edge Of Winter",
    [13771] = "A Valiant's Field Training",
    [13772] = "The Grand Melee",
    [13773] = "A Blade Fit For A Champion",
    [13774] = "A Worthy Weapon",
    [13775] = "The Edge Of Winter",
    [13776] = "A Valiant's Field Training",
    [13777] = "The Grand Melee",
    [13778] = "A Blade Fit For A Champion",
    [13779] = "A Worthy Weapon",
    [13780] = "The Edge Of Winter",
    [13781] = "A Valiant's Field Training",
    [13782] = "The Grand Melee",
    [13783] = "A Blade Fit For A Champion",
    [13784] = "A Worthy Weapon",
    [13785] = "The Edge Of Winter",
    [13786] = "A Valiant's Field Training",
    [13787] = "The Grand Melee",
    [13788] = "Threat From Above",
    [13789] = "Taking Battle To The Enemy",
    [13790] = "Among the Champions",
    [13791] = "Taking Battle To The Enemy",
    [13793] = "Among the Champions",
    [13794] = "Eadric the Pure",
    [13795] = "The Scourgebane",
    [13809] = "Threat From Above",
    [13810] = "Taking Battle To The Enemy",
    [13811] = "Among the Champions",
    [13812] = "Threat From Above",
    [13813] = "Taking Battle To The Enemy",
    [13814] = "Among the Champions",
    [13828] = "Mastery Of Melee",
    [13829] = "Mastery Of Melee",
    [13835] = "Mastery Of The Shield-Breaker",
    [13837] = "Mastery Of The Charge",
    [13838] = "Mastery Of The Shield-Breaker",
    [13839] = "Mastery Of The Charge",
    [13846] = "Contributin' To The Cause",
    [13847] = "At The Enemy's Gates",
    [13851] = "At The Enemy's Gates",
    [13852] = "At The Enemy's Gates",
    [13854] = "At The Enemy's Gates",
    [13855] = "At The Enemy's Gates",
    [13856] = "At The Enemy's Gates",
    [13857] = "At The Enemy's Gates",
    [13858] = "At The Enemy's Gates",
    [13859] = "At The Enemy's Gates",
    [13860] = "At The Enemy's Gates",
    [13861] = "Battle Before The Citadel",
    [13862] = "Battle Before The Citadel",
    [13863] = "Battle Before The Citadel",
    [13864] = "Battle Before The Citadel",
    [14016] = "The Black Knight's Curse",
    [14017] = "The Black Knight's Fate",
    [14074] = "A Leg Up",
    [14076] = "Breakfast Of Champions",
    [14077] = "The Light's Mercy",
    [14080] = "Stop The Aggressors",
    [14090] = "Gormok Wants His Snobolds",
    [14092] = "Breakfast Of Champions",
    [14095] = "Identifying the Remains",
    [14096] = "You've Really Done It This Time, Kul",
    [14101] = "Drottinn Hrothgar",
    [14102] = "Mistcaller Yngvar",
    [14104] = "Ornolf The Scarred",
    [14105] = "Deathspeaker Kharos",
    [14107] = "The Fate Of The Fallen",
    [14108] = "Get Kraken!",
    [14112] = "What Do You Feed a Yeti, Anyway?",
    [14136] = "Rescue at Sea",
    [14140] = "Stop The Aggressors",
    [14141] = "Gormok Wants His Snobolds",
    [14142] = "You've Really Done It This Time, Kul",
    [14143] = "A Leg Up",
    [14144] = "The Light's Mercy",
    [14145] = "What Do You Feed a Yeti, Anyway?",
    [14152] = "Rescue at Sea",
    [14441] = "Garrosh's Autograph",
    [14443] = "The Battered Hilt",
    [14444] = "What The Dragons Know",
    [24442] = "Battle Plans Of The Kvaldir",
    [24454] = "Return To Caladis Brightspear",
    [24461] = "Reforging The Sword",
    [24476] = "Tempering The Blade",
    [24480] = "The Halls Of Reflection",
    [24522] = "Journey To The Sunwell",
    [24553] = "The Purification of Quel'Delar",
    [24554] = "The Battered Hilt",
    [24555] = "What The Dragons Know",
    [24558] = "Return To Myralion Sunblaze",
    [24559] = "Reforging The Sword",
    [24560] = "Tempering The Blade",
    [24561] = "The Halls Of Reflection",
    [24562] = "Journey To The Sunwell",
    [24564] = "The Purification of Quel'Delar",
    [24594] = "The Purification of Quel'Delar",
    [24595] = "The Purification of Quel'Delar",
    [24596] = "The Purification of Quel'Delar",
    [24598] = "The Purification of Quel'Delar",
    [24795] = "A Victory For The Silver Covenant",
    [24796] = "A Victory For The Silver Covenant",
    [24798] = "A Victory For The Sunreavers",
    [24799] = "A Victory For The Sunreavers",
    [24800] = "A Victory For The Sunreavers",
    [24801] = "A Victory For The Sunreavers",
}

local function BuildQuestEntries(ids, npcLabel)
    local quests = {}
    for i = 1, #ids do
        local id = ids[i]
        local name = ICECROWN_QUEST_NAMES[id] or ("Icecrown Quest " .. id)
        quests[#quests + 1] = { id = id, name = name, npc = npcLabel or "Icecrown Campaign" }
    end
    return quests
end

-- =============================================================================
-- Wrath of the Lich King: The Frozen Throne (Arthas Menethil)
-- A curated campaign of quests and dungeons centered on Arthas' fall.
-- =============================================================================

SM.FrozenThroneData = {
    title = "The Frozen Throne",
    achievementName = "Arthas Menethil",
    achievements = {
        -- Dragonblight / Wrathgate
        35,     -- Might of Dragonblight (full Dragonblight zone story)
        547,    -- Veteran of the Wrathgate (the Wrathgate chain specifically)
        -- Icecrown questing
        40,     -- Icecrown: The Final Goal (full Icecrown zone story)
        -- Northrend-wide
        41,     -- Loremaster of Northrend
        -- Icecrown Citadel — instance clears
        4531,   -- Storming the Citadel (10 player)
        4604,   -- Storming the Citadel (25 player)
        4528,   -- The Plagueworks (10 player)
        4605,   -- The Plagueworks (25 player)
        4529,   -- The Crimson Hall (10 player)
        4606,   -- The Crimson Hall (25 player)
        4527,   -- The Frostwing Halls (10 player)
        4607,   -- The Frostwing Halls (25 player)
        4532,   -- Fall of the Lich King (10 player)
        4608,   -- Fall of the Lich King (25 player)
        4636,   -- Heroic: Fall of the Lich King (10 player)
        4637,   -- Heroic: Fall of the Lich King (25 player)
        -- Icecrown Citadel — Lich King encounter
        4530,   -- The Frozen Throne (10 player) — grants Kingslayer title
        4597,   -- The Frozen Throne (25 player)
        4601,   -- Been Waiting a Long Time for This (10 player)
        4621,   -- Been Waiting a Long Time for This (25 player)
        4581,   -- Neck-Deep in Vile (10 player)
        4622,   -- Neck-Deep in Vile (25 player)
        -- Icecrown Citadel — Glory meta
        4602,   -- Glory of the Icecrown Raider (10 player)
        4603,   -- Glory of the Icecrown Raider (25 player)
    },
    description = "Follow Arthas Menethil's path from prince to Lich King through the Dragonblight war campaign, the Wrathgate catastrophe, and the final push into Icecrown Citadel to end his reign.",
    zone = "Dragonblight / Icecrown",
    expansion = "Wrath of the Lich King",
    color = { 0.45, 0.72, 0.95 },  -- Icy blue
    icon = 341221,

    startQuest = { id = 12495, name = "Audience With The Dragon Queen", npc = "Alexstrasza the Life-Binder", location = "Wyrmrest Temple, Dragonblight" },
    startMapID = 115, -- Dragonblight
    startX = 0.5900,
    startY = 0.5400,

    npcLocations = {
        -- Key figures
        ["Alexstrasza the Life-Binder"] = { mapID = 115, x = 0.5900, y = 0.5400 },
        ["Highlord Bolvar Fordragon"]  = { mapID = 115, x = 0.7610, y = 0.6310 },
        ["Saurfang the Younger"]       = { mapID = 115, x = 0.3780, y = 0.2300 },
        ["Highlord Tirion Fordring"]   = { mapID = 118, x = 0.7600, y = 0.2000 },
        ["Thassarian"]                 = { mapID = 118, x = 0.7900, y = 0.7200 },
        ["Koltira Deathweaver"]        = { mapID = 118, x = 0.4300, y = 0.1900 },
        ["Lady Jaina Proudmoore"]      = { mapID = 125, x = 0.5500, y = 0.8600 },
        ["Lady Sylvanas Windrunner"]   = { mapID = 125, x = 0.5500, y = 0.8600 },
        ["Martin Victus"]              = { mapID = 125, x = 0.5600, y = 0.5700 },
    },

    npcDisplayIDs = {
        ["Alexstrasza the Life-Binder"] = 24560,
        ["Highlord Bolvar Fordragon"]  = 5566,
        ["Saurfang the Younger"]       = 31785,
        ["Highlord Tirion Fordring"]   = 31011,
        ["Thassarian"]                 = 26608,
        ["Koltira Deathweaver"]        = 25048,
        ["Lady Jaina Proudmoore"]      = 2970,
        ["Lady Sylvanas Windrunner"]   = 28213,
        ["Martin Victus"]              = 30696,
        ["Emissary Brighthoof"]        = 23805,
        ["High Commander Halford Wyrmbane"] = 24348,
        ["Chief Plaguebringer Middleton"] = 30007,
        ["Chromie"]                   = 24877,
        ["Baron Sliver"]              = 28407,
        ["Vereth the Cunning"]        = 29145,
        ["Matthias Lehner"]           = 27522,
        ["Gorkun Ironskull"]          = 27937,
        ["Dark Ranger Vorel"]         = 30686,
    },

    chapterDisplayIDs = {
        ["Recruiting the Taunka"]     = 23805,  -- Emissary Brighthoof
        ["Destroy the Nerubians"]     = 23806,  -- Overlord Agmar
        ["Annexing the Taunka"]       = 23976,  -- Icemist
        ["The Forsaken Plague"]       = 23875,  -- Middleton
        ["The Red Dragonflight"]      = 23806,  -- Overlord Agmar
        ["Victory Over the Scourge"]  = 23034,  -- Saurfang the Younger
        ["The Dragonblight Campaign"]  = 24351,  -- Duke August Foehammer
        ["The Red Dragonflight (Alliance)"] = 24879,  -- Highlord Bolvar Fordragon
        ["Victory Over the Scourge (Alliance)"] = 24879,  -- Highlord Bolvar Fordragon
        ["The Frozen Halls"]          = 30696,  -- Martin Victus
    },

    chapters = {
        {
            chapter = "The Dragonblight Campaign",
            summary = "Establish the Alliance foothold in Dragonblight at Wintergarde Keep.",
            recap = "Wintergarde Keep stands as a beacon against the endless undead tide. High Commander Halford Wyrmbane and Duke August Foehammer have established the Alliance's foothold in Dragonblight, but Naxxramas hovers overhead like a death sentence, raining plague and terror on the front lines. You fight through the Carrion Fields, man siege engines against plague wagons, and push into the depths of the Wintergarde Mausoleum itself. Behind you, the 7th Legion holds the line. Ahead, Lord Bolvar Fordragon awaits at Angrathar — the Wrathgate. But every step forward is bought with blood, and the Scourge does not rest.",
            portraitDisplayID = 24351,
            faction = "Alliance",
            quests = {
                { id = 12325, name = "Into Hostile Territory", npc = "Duke August Foehammer", faction = "Alliance" },
                { id = 12326, name = "Steamtank Surprise", npc = "Duke August Foehammer", faction = "Alliance" },
                { id = 12455, name = "Scattered To The Wind", npc = "Ambo Cash", faction = "Alliance" },
                { id = 12457, name = "The Chain Gun And You", npc = "Ambo Cash", faction = "Alliance" },
                { id = 12463, name = "Plunderbeard Must Be Found!", npc = "Ambo Cash", faction = "Alliance" },
                { id = 12465, name = "Plunderbeard's Journal", npc = "Ambo Cash", faction = "Alliance" },
                { id = 12466, name = "Chasing Icestorm: The 7th Legion Front", npc = "Ambo Cash", faction = "Alliance" },
                { id = 12467, name = "Chasing Icestorm: Thel'zan's Phylactery", npc = "Legion Commander Tyralion", faction = "Alliance" },
                { id = 12472, name = "Finality", npc = "Legion Commander Yorik", faction = "Alliance" },
                { id = 12473, name = "An End And A Beginning", npc = "Legion Commander Yorik", faction = "Alliance" },
                { id = 12474, name = "To Fordragon Hold!", npc = "High Commander Halford Wyrmbane", faction = "Alliance" },
            },
        },
        {
            chapter = "Recruiting the Taunka",
            summary = "Recruit the Taunka as allies for the Horde in Dragonblight.",
            recap = "The Horde's banner flies over Agmar's Hammer, but the Scourge surrounds on all sides. Worse, the Taunka — great polar tauren of the north — have been captured by the Anub'ar, dragged into the darkness below Dragonblight to serve the Lich King. Emissary Brighthoof speaks of blood oaths and ancient bonds. Overlord Agmar demands action. You descend into the pits and bring the Taunka out — or what remains of them. The survivors are broken, but unbroken. They pledge themselves to the Horde, their blood mingling with yours in a ritual as old as the earth itself. Every alliance costs something. This one costs blood.",
            portraitDisplayID = 23806,
            faction = "Horde",
            quests = {
                { id = 11978, name = "Into the Fold", npc = "Emissary Brighthoof", faction = "Horde" },
                { id = 11983, name = "Blood Oath of the Horde", npc = "Emissary Brighthoof", faction = "Horde" },
                { id = 12008, name = "Agmar's Hammer", npc = "Overlord Agmar", faction = "Horde" },
            },
        },
        {
            chapter = "Destroy the Nerubians",
            summary = "Crush the Anub'ar Nerubians threatening the Horde's flank in Dragonblight.",
            recap = "The Anub'ar Nerubians are a wound in the Horde's side — spider-warriors burrowing up from Azjol-Nerub, striking at supply lines and patrols. Overlord Agmar will not have his flank exposed. Senior Sergeant Juktok leads the assault into the Pit of Narjun, Valnok Windrager brings wyverns to the sky, and you cut a path through the chittering darkness. The Nerubians serve the Lich King, and everything that serves him must die. Victory is not a guarantee — it is a demand.",
            portraitDisplayID = 23806,
            faction = "Horde",
            quests = {
                { id = 12034, name = "Victory Nears...", npc = "Overlord Agmar", faction = "Horde" },
                { id = 12036, name = "From the Depths of Azjol-Nerub", npc = "Senior Sergeant Juktok", faction = "Horde" },
                { id = 12053, name = "The Might of the Horde", npc = "Senior Sergeant Juktok", faction = "Horde" },
                { id = 12071, name = "Attack by Air!", npc = "Valnok Windrager", faction = "Horde" },
                { id = 12072, name = "Blightbeasts be Damned", npc = "Valnok Windrager", faction = "Horde" },
            },
        },
        {
            chapter = "Annexing the Taunka",
            summary = "Free High Chief Icemist and formally integrate the Taunka into the Horde.",
            recap = "The Taunka have given their word, but the Anub'ar still hold their High Chief captive in the depths below. Greatmother Icemist begs for her son's release. Banthok Icemist leads you into the darkness one more time, through chains and webs and the clicking horror of the Nerubian lords. You find High Chief Icemist in chains, broken but defiant. The rescue becomes a war. And when you finally bring him to the surface, Roanauk Icemist stands before the Horde as its newest chief — blood-sworn, oath-bound, and ready to die for a cause that was not always his own.",
            portraitDisplayID = 23976,
            faction = "Horde",
            quests = {
                { id = 12063, name = "Strength of Icemist", npc = "Greatmother Icemist", faction = "Horde" },
                { id = 12064, name = "Chains of the Anub'ar", npc = "Banthok Icemist", faction = "Horde" },
                { id = 12069, name = "Return of the High Chief", npc = "Banthok Icemist", faction = "Horde" },
                { id = 12140, name = "All Hail Roanauk!", npc = "Roanauk Icemist", faction = "Horde" },
            },
        },
        {
            chapter = "The Forsaken Plague",
            summary = "Test the Forsaken blight weapon in the Carrion Fields.",
            recap = "In the shadow of the war, the Forsaken have been busy. Chief Plaguebringer Middleton has created something new — a blight that can kill the Scourge where steel cannot. But the formula needs testing, and volunteers are hard to find. You become the test subject, handling substances that would melt your flesh, inhaling fumes that would stop your heart, and spreading the good word of wholesale chemical warfare. The Forsaken call it progress. The Scourge will call it death. Middleton smiles through gritted teeth and tells you not to worry — the first dose is always the worst.",
            portraitDisplayID = 23875,
            faction = "Horde",
            quests = {
                { id = 12189, name = "Imbeciles Abound!", npc = "Chief Plaguebringer Middleton", faction = "Horde" },
                { id = 12188, name = "The Forsaken Blight and You: How Not to Die", npc = "Chief Plaguebringer Middleton", faction = "Horde" },
                { id = 12200, name = "Emerald Dragon Tears", npc = "Chief Plaguebringer Middleton", faction = "Horde" },
                { id = 12218, name = "Spread the Good Word", npc = "Chief Plaguebringer Middleton", faction = "Horde" },
                { id = 12221, name = "The Forsaken Blight", npc = "Doctor Sintar Malefious", faction = "Horde" },
            },
        },
        {
            chapter = "The Red Dragonflight (Alliance)",
            summary = "Seek aid from Alexstrasza and the Red Dragonflight at Wyrmrest Temple.",
            recap = "The Alliance has bled for Dragonblight. Now Highlord Bolvar Fordragon takes you to Wyrmrest Temple, to the throne of Alexstrasza the Life-Binder. The Dragon Queen has kept her distance from this war, but the Scourge threatens her children as surely as it threatens every living thing. She agrees to lend her strength — not out of love for the Alliance, but out of hatred for the Lich King. You take to the skies on ruby wings, bearing the fire of the Aspects against the frozen horror ahead. The dragons have chosen their side. Now the real war begins.",
            portraitDisplayID = 24879,
            faction = "Alliance",
            quests = {
                { id = 12495, name = "Audience With The Dragon Queen", npc = "Highlord Bolvar Fordragon", faction = "Alliance" },
                { id = 12497, name = "Galakrond and the Scourge", npc = "Alexstrasza the Life-Binder" },
                { id = 12498, name = "On Ruby Wings", npc = "Torastrasza" },
            },
        },
        {
            chapter = "The Red Dragonflight",
            summary = "Seek aid from Alexstrasza and the Red Dragonflight at Wyrmrest Temple.",
            recap = "The Horde's forces are gathered, the Taunka blood-sworn, and the Nerubian threat crushed. Saurfang the Younger takes you to Wyrmrest Temple, where Alexstrasza the Life-Binder watches the war with ancient, weary eyes. The Dragon Queen has little love for the Horde, but she hates the Lich King more. She agrees to bring her dragons to bear against the Scourge. You fly on ruby wings over the blighted fields of Dragonblight, carrying fire and fury against the undead. The Aspects have spoken. Angrathar awaits.",
            portraitDisplayID = 23806,
            faction = "Horde",
            quests = {
                { id = 12224, name = "The Kor'kron Vanguard!", npc = "Saurfang the Younger", faction = "Horde" },
                { id = 12496, name = "Audience With The Dragon Queen", npc = "Saurfang the Younger", faction = "Horde" },
                { id = 12497, name = "Galakrond and the Scourge", npc = "Alexstrasza the Life-Binder" },
                { id = 12498, name = "On Ruby Wings", npc = "Torastrasza" },
            },
        },
        {
            chapter = "Victory Over the Scourge (Alliance)",
            summary = "March to Angrathar and the Wrathgate.",
            recap = "Angrathar. The Wrathgate. The final approach to Icecrown Citadel, where the Lich King waits in his frozen throne. Fordragon has committed every soldier, every dragon, every ounce of strength the Alliance has left. The gate looms ahead, carved from black ice and old nightmares. Beyond it lies the Scourge's heart. The Horde marches beside you — an uneasy alliance forged in the fire of common purpose. You reach the gate. The battle is joined. And then the Forsaken turn their weapons on you. The blight erupts. Soldiers choke, fall, dissolve. The Horde betrays the Alliance, and the Scourge finishes what they started. Fordragon is consumed by flame. The Alliance breaks. Whatever victory was possible died in the green cloud of the blight.",
            portraitDisplayID = 24879,
            faction = "Alliance",
            quests = {
                { id = 12499, name = "Return To Angrathar", npc = "Highlord Bolvar Fordragon", faction = "Alliance" },
            },
        },
        {
            chapter = "Victory Over the Scourge",
            summary = "March to Angrathar and the Wrathgate.",
            recap = "Angrathar. The Wrathgate. The path to the Lich King's door. Saurfang the Younger leads the Horde's final push, every Orc blood-mad and ready to die. The Alliance marches beside you — an uneasy alliance of necessity. Ahead, the Scourge waits in endless ranks. Above, dragons circle. The gate itself is carved from the bones of giants, a monument to death that has stood for ten thousand years. You have fought across all of Northrend to reach this moment. The battle begins. The Lich King's forces crack. And then the Forsaken unleash the blight — not on the Scourge, but on everyone. Both factions. Both armies. The green cloud rises, and soldiers on both sides fall screaming. The Horde has betrayed the Alliance. The Scourge advances through the dying. Nothing will ever be the same.",
            portraitDisplayID = 23034,
            faction = "Horde",
            quests = {
                { id = 12500, name = "Return To Angrathar", npc = "Saurfang the Younger", faction = "Horde" },
            },
        },
        {
            chapter = "The Culling of Stratholme",
            note = "Travel to the Caverns of Time in Tanaris and speak with Chromie to enter the Culling of Stratholme.",
            summary = "Travel through time to Stratholme and witness the moment that pushes Prince Arthas over the edge.",
            recap = "In the Culling of Stratholme, the Bronze Dragonflight sends you to stop the Infinite Dragonflight from rewriting history. You witness Arthas at the tipping point: a prince convinced that mercy is weakness and that any sacrifice is justified to stop the Scourge.",
            quests = {
                { id = 13149, name = "Dispelling Illusions", npc = "Chromie" },
                { id = 13151, name = "A Royal Escort", npc = "Chromie" },
            },
        },
        {
            chapter = "The Shadow Vault",
            summary = "Break the Scourge hold at the Shadow Vault and establish a forward base for the war in Icecrown.",
            recap = "The assault shifts to Icecrown proper. You strike into the Shadow Vault, shatter one of the Lich King's command outposts, and open a staging point for deeper pushes toward the citadel.",
            quests = {
                { id = 12899, name = "The Shadow Vault", npc = "Baron Sliver" },
                { id = 13083, name = "Light Within the Darkness", npc = "Highlord Tirion Fordring" },
            },
        },
        {
            chapter = "The Argent Vanguard",
            summary = "Hold the Argent Vanguard and carve the first stable frontline against the Scourge in Icecrown.",
            recap = "Icecrown begins as a defensive nightmare. You reinforce the Argent Vanguard, repel relentless undead pressure, and help reopen routes that become the backbone for every assault that follows.",
            quests = {
                { id = 13145, name = "The Vile Hold", npc = "Vereth the Cunning" },
                { id = 13300, name = "Slaves to Saronite", npc = "Thassarian" },
                { id = 13036, name = "Honor Above All Else", npc = "Crusade Commander Entari" },
                { id = 13039, name = "Defending The Vanguard", npc = "Crusader Lord Dalfors" },
                { id = 13086, name = "The Last Line Of Defense", npc = "Siegemaster Fezzik" },
                { id = 13104, name = "Once More Unto The Breach, Hero", npc = "Siegemaster Fezzik", faction = "Alliance" },
                { id = 13105, name = "Once More Unto The Breach, Hero", npc = "Siegemaster Fezzik", faction = "Horde" },
                { id = 13219, name = "The Unthinkable", npc = "Vereth the Cunning" },
            },
        },
        {
            chapter = "The Gates of Icecrown",
            summary = "Crack the outer defenses at Corp'rethar and Aldur'thar to clear the path to Icecrown Citadel.",
            recap = "To reach the citadel, the Scourge gate network must fall. You sabotage command posts, scout death gates, and eliminate key guardians holding the final approaches to Arthas' fortress.",
            quests = {
                { id = 13338, name = "The Guardians of Corp'rethar", npc = "Thassarian" },
                { id = 13351, name = "Sneak Preview", npc = "Thassarian", faction = "Horde" },
                { id = 13318, name = "Drag and Drop", npc = "Thassarian", faction = "Alliance" },
                { id = 13403, name = "Tirion's Gambit", npc = "Highlord Tirion Fordring" },
                { id = 13346, name = "No Rest For The Wicked", npc = "Thassarian", faction = "Alliance" },
                { id = 13367, name = "No Rest For The Wicked", npc = "Koltira Deathweaver", faction = "Horde" },
            },
        },
        {
            chapter = "Sindragosa's Fall",
            summary = "Hunt answers in the dragon graveyards where Arthas' deepest secrets begin to surface.",
            recap = "At Sindragosa's Fall and the Court of Bones, scattered clues become a coherent truth about Arthas' fate, his bond to Frostmourne, and the only path to ending him.",
            quests = {
                { id = 13305, name = "Do Your Worst", npc = "Matthias Lehner" },
                { id = 13395, name = "Army of the Damned", npc = "Matthias Lehner" },
                { id = 13348, name = "Futility", npc = "Thassarian" },
                { id = 13397, name = "Sindragosa's Fall", npc = "Thassarian", faction = "Alliance" },
                { id = 13349, name = "Cradle of the Frostbrood", npc = "Koltira Deathweaver", faction = "Horde" },
                { id = 13398, name = "Where Dragons Fell", npc = "Matthias Lehner", faction = "Alliance" },
                { id = 13359, name = "Where Dragons Fell", npc = "Matthias Lehner", faction = "Horde" },
                { id = 13399, name = "Time for Answers", npc = "Matthias Lehner" },
                { id = 13400, name = "The Hunter and the Prince", npc = "Matthias Lehner", faction = "Alliance" },
                { id = 13361, name = "The Hunter and the Prince", npc = "Matthias Lehner", faction = "Horde" },
                { id = 13401, name = "Knowledge is a Terrible Burden", npc = "Thassarian", faction = "Alliance" },
                { id = 13362, name = "Knowledge is a Terrible Burden", npc = "Koltira Deathweaver", faction = "Horde" },
                { id = 13402, name = "Tirion's Help", npc = "Thassarian", faction = "Alliance" },
                { id = 13363, name = "Argent Aid", npc = "Koltira Deathweaver", faction = "Horde" },
            },
        },
        {
            chapter = "The Frozen Halls",
            note = "Talk to Dark Ranger Vorel in Dalaran to begin. You need to be in the Wrath of the Lich King version of Dalaran — fly to Northrend and land there. Runs through three dungeons: Forge of Souls, Pit of Saron, and Halls of Reflection.",
            summary = "Strike through the Frozen Halls — Forge of Souls, Pit of Saron, and Halls of Reflection — to reach Frostmourne.",
            recap = "You lead a covert strike through three dungeons — the Forge of Souls, the Pit of Saron, and the Halls of Reflection — to reach Frostmourne itself. Uther's spirit reveals the truth of Arthas' final weakness and the cost of ending the Lich King forever.",
            quests = {
                -- Alliance
                { id = 24510, name = "Inside the Frozen Citadel", npc = "Lady Jaina Proudmoore", faction = "Alliance" },
                { id = 24499, name = "Echoes of Tortured Souls", npc = "Lady Jaina Proudmoore", faction = "Alliance" },
                { id = 24683, name = "The Pit of Saron", npc = "Lady Jaina Proudmoore", faction = "Alliance" },
                { id = 24498, name = "The Path to the Citadel", npc = "Martin Victus" },
                { id = 24710, name = "Deliverance from the Pit", npc = "Martin Victus", faction = "Alliance" },
                { id = 24711, name = "Frostmourne", npc = "Jaina Proudmoore", faction = "Alliance" },
                -- Horde
                { id = 24506, name = "Inside the Frozen Citadel", npc = "Dark Ranger Vorel", faction = "Horde" },
                { id = 24511, name = "Echoes of Tortured Souls", npc = "Lady Sylvanas Windrunner", faction = "Horde" },
                { id = 24682, name = "The Pit of Saron", npc = "Lady Sylvanas Windrunner", faction = "Horde" },
                { id = 24712, name = "Deliverance from the Pit", npc = "Gorkun Ironskull", faction = "Horde" },
                { id = 24713, name = "Frostmourne", npc = "Sylvanas Windrunner", faction = "Horde" },
            },
        },
        {
            chapter = "Icecrown's End",
            achievementID = 4608,
            note = "Defeat the Lich King in Icecrown Citadel — fully soloable at max level.",
            summary = "The Lich King's reign ends at the Frozen Throne.",
            recap = "Arthas died at the Frozen Throne. The moment he fell, the power of the Lich King's realm rippled outward. The war in Northrend is finally over, but the cost — and what comes after — will echo through history.",
            quests = {},
        },
    },
}
